### ISSUE TITLE
CodeKit (.kit)

### ISSUE THREAD

**Issue by churchs19** [EmmanuelBeziat/vscode-great-icons#1]
I'd love to see an icon for CodeKit files (.kit). 

[https://incident57.com/codekit/](https://incident57.com/codekit/)

This is a great icon set. Thanks!

**Comment by EmmanuelBeziat** [comment]
Here you go! v1.0.8 is published, with codekit added.

Thanks for your request, hope you'ell enjoy!

**Comment by churchs19** [comment]
Thanks! Great job!
