### ISSUE TITLE
Add Visual Foxpro icon

### ISSUE THREAD

**Issue by mdacunha90** [EmmanuelBeziat/vscode-great-icons#101]
http://www.congruentsoft.com/visual-foxpro-to-dot-net-migration.aspx

![foxpro-icon](https://user-images.githubusercontent.com/16214003/36839327-153ab516-1d42-11e8-8d58-60dff4a0a6fb.png)

**Comment by EmmanuelBeziat** [comment]
Hi @mdacunha90 ,

I need to know the file extensions to be used with the icon. Can you make a list of them?

Thanks.

**Comment by mdacunha90** [comment]
Hi @EmmanuelBeziat 

The file extensions to be used with the icon are:

-  .prg
-  .fxp

Thanks.

**Comment by EmmanuelBeziat** [comment]
Hi,

Check out the new v2.1.28!

Thanks for making VSCode Great Icons a better set! :)

**Comment by APerricone** [comment]
Hi mdacunha90, do you use visual foxpro?
with [my extension](https://marketplace.visualstudio.com/items?itemName=aperricone.harbour) the prg file are harbour/xHarbour file and the image is another [https://harbour.github.io/logo](https://harbour.github.io/logo) 
Anyway, for me is ok see a fox on prg files and this theme is great.
I am just curious about foxpro...

**Comment by EmmanuelBeziat** [comment]
Hi @APerricone 

Yeah, that's the problem about extensions files… 😞 I might try to add a poll for that, but I'm not sure people would come by to check, especially if many don't know this filetype.

I didn't know about foxpro and harbour before this topic, but I might add them both and use the most used for `.prg`.

By the way, I can add Harbour anyway, what are the other files extensions it use? 

@mdacunha90 do you have a view on that?

**Comment by APerricone** [comment]
Hello,
they are both dialect of clipper, so have the same extension... for me is ok the default icon for prg file, i was surprise about the fox :)
It is not necessary work for it :+1:

**Comment by mdacunha90** [comment]
Hi  @APerricone <https://github.com/aperricone>,

Yes I use Foxpro in a daily bases at my job with my 3 collegues.

Cordialement, Mit freundlichen Grüßen, Best Regards, Mat frëndleche Gréiss,
Mickael GOMES



------------------------------

[image: Afficher l'image d'origine]

Zone Industrielle Riedgen

Ancien Site WSA

L-3451 Dudelange

Tel. : +352.51.22.32.165

Numéro court : 352 165




------------------------------

​[image:
https://lh5.googleusercontent.com/QEV3br2N5HcJHrOdDxHPD9-Lh2ZaEn6pwfZsCQ0t5T1d8E0wVjbQDCPv8OSMVcFHirbJ5JzxjmdVWu75PoZxd2Lf69vPUSSR0n6sON2RNayG0ONsj4iNJMxsAQ]
  Avant d'imprimer, pensez à l'environnement !
*Cet e-mail est destiné exclusivement aux personnes dont le nom figure
ci-dessus. Il peut contenir des informations protégées par le secret
professionnel et dont la divulgation est strictement prohibée. Si vous avez
reçu cet e-mail par erreur, nous vous remercions de bien vouloir le
détruire immédiatement et de nous en informer par e-mail.*
*This e-mail is intended for the above-mentioned addressees only. It may
contain privileged or confidential information, the review, dissemination
or disclosure of which is strictly prohibited. If you have received this
e-mail by mistake please immediately destroy it and so inform us by e-mail.*

2018-03-11 16:18 GMT+01:00 Antonino Perricone <notifications@github.com>:

**Comment by APerricone** [comment]
Hi Mickael,
Me and other 3.400 users use harbor with vscode.
my extension register the filetype harbour, maybe if it is not installed this filetype does not exist and maybe it is possible say "if the extension is prg put the fox, if the file type is harbour put other icon" in this case only who have the extension installed see the other icon...
Or, to avoid discussion, put the default icon.
Antonino

**Comment by mdacunha90** [comment]
Hi,

I don't know how much people use foxpro in vscode, I just can say that it
is a Microsoft product and that there is a french community of
professional users
that counts 3815 members.

Cordialement, Mit freundlichen Grüßen, Best Regards, Mat frëndleche Gréiss,
Mickael GOMES



------------------------------

[image: Afficher l'image d'origine]

Zone Industrielle Riedgen

Ancien Site WSA

L-3451 Dudelange

Tel. : +352.51.22.32.165

Numéro court : 352 165




------------------------------

​[image:
https://lh5.googleusercontent.com/QEV3br2N5HcJHrOdDxHPD9-Lh2ZaEn6pwfZsCQ0t5T1d8E0wVjbQDCPv8OSMVcFHirbJ5JzxjmdVWu75PoZxd2Lf69vPUSSR0n6sON2RNayG0ONsj4iNJMxsAQ]
  Avant d'imprimer, pensez à l'environnement !
*Cet e-mail est destiné exclusivement aux personnes dont le nom figure
ci-dessus. Il peut contenir des informations protégées par le secret
professionnel et dont la divulgation est strictement prohibée. Si vous avez
reçu cet e-mail par erreur, nous vous remercions de bien vouloir le
détruire immédiatement et de nous en informer par e-mail.*
*This e-mail is intended for the above-mentioned addressees only. It may
contain privileged or confidential information, the review, dissemination
or disclosure of which is strictly prohibited. If you have received this
e-mail by mistake please immediately destroy it and so inform us by e-mail.*

2018-03-12 9:18 GMT+01:00 Antonino Perricone <notifications@github.com>:

**Comment by APerricone** [comment]
Hi,
[There is no new version from 2007](https://en.wikipedia.org/wiki/Visual_FoxPro)
I think the better solution is put the default icon for prg files.
Antonino

**Comment by EmmanuelBeziat** [comment]
Hi,

As it's possible to have icons by environment rather than by file extension, I'll try to have the both icons working for their respective workspace.

By default, I'll put the Harbor icon on .prg files, as it's still maintained.

**Comment by EmmanuelBeziat** [comment]
It's done, check out the new version.
Thanks!

**Comment by mdacunha90** [comment]
Hello,

I now have the harbor logo and I'm using foxpro!

So many people using using harbor as Antonino said but no one ever asked
for it until I asked for the Foxpro icon.

Cordialement, Mit freundlichen Grüßen, Best Regards, Mat frëndleche Gréiss,
Mickael GOMES



------------------------------

[image: Afficher l'image d'origine]

Zone Industrielle Riedgen

Ancien Site WSA

L-3451 Dudelange

Tel. : +352.51.22.32.165

Numéro court : 352 165




------------------------------

​[image:
https://lh5.googleusercontent.com/QEV3br2N5HcJHrOdDxHPD9-Lh2ZaEn6pwfZsCQ0t5T1d8E0wVjbQDCPv8OSMVcFHirbJ5JzxjmdVWu75PoZxd2Lf69vPUSSR0n6sON2RNayG0ONsj4iNJMxsAQ]
  Avant d'imprimer, pensez à l'environnement !
*Cet e-mail est destiné exclusivement aux personnes dont le nom figure
ci-dessus. Il peut contenir des informations protégées par le secret
professionnel et dont la divulgation est strictement prohibée. Si vous avez
reçu cet e-mail par erreur, nous vous remercions de bien vouloir le
détruire immédiatement et de nous en informer par e-mail.*
*This e-mail is intended for the above-mentioned addressees only. It may
contain privileged or confidential information, the review, dissemination
or disclosure of which is strictly prohibited. If you have received this
e-mail by mistake please immediately destroy it and so inform us by e-mail.*

2018-03-18 14:51 GMT+01:00 Emmanuel Béziat <notifications@github.com>:

**Comment by APerricone** [comment]
I propose to remove the prg association.
there is a lot of dialect:

- harbour
- xHarbour
- FoxPro
- xBase
- FlagShip
- X#
- Vulcan.NET
- Visual Objects

and all uses prg extension...

**Comment by EmmanuelBeziat** [comment]
Then I'll just put a simple grind.

Check the new v2.1.30.
