### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by viniciusCamargo** [EmmanuelBeziat/vscode-great-icons#102]
## [Kotlin](https://kotlinlang.org/)

* [SVG/PNG](https://commons.wikimedia.org/wiki/File:Kotlin-logo.svg)
![image](https://user-images.githubusercontent.com/2068530/37056317-d719d67a-2162-11e8-8993-d4996d1d54ed.png)
* Files extensions: *.kt, *.kts

Thanks! :smile:

**Comment by EmmanuelBeziat** [comment]
Hi,

Check out the new v2.1.28!

Thanks for making VSCode Great Icons a better set! :)
