### ISSUE TITLE
Add support for pascal files

### ISSUE THREAD

**Issue by pakLebah** [EmmanuelBeziat/vscode-great-icons#103]
Please, add support for (object) pascal files. Here's the details:

- `.pas` or `.pp` extension for pascal code file, using this logo:
    - ala [Free Pascal](http://freepascal.org) is cheetah head, something like [this](http://east.slcschools.org/brand/images/East-High-Spirit-LeopardHead-Black-OFFICE.png), or [this](https://media.istockphoto.com/vectors/cheetah-head-vector-id165602808), or [this](http://laoblogger.com/images/2-jaguars-clipart-6.jpg).
    - ala [Delphi](http://embarcadero.com/products/delphi) is roman helmet like [this](https://rpottsoh.keybase.pub/Delphi.png) or [this](https://www.shareicon.net/data/512x512/2016/06/19/603729_prog_512x512.png).

- `.dpr` or `.lpr` extension for pascal project file, using this logo:
    - ala Free Pascal is cheetah paw, something like [this](http://wiki.lazarus.freepascal.org/images/2/25/paw.png), or [this](http://weclipart.com/gimg/7F9556607DE2600B/zxig5K4cA.png).
    - ala Delphi is roman building like [this](http://i.imgur.com/nXVVQHw.png) or [this](https://n6-img-fp.akamaized.net/free-icon/bank-symbol_318-83749.jpg).

Though personally I prefer the cheetah theme ala Free Pascal, but the "official" icons don't look really good. I just don't have the skill to make a great icon.

However, I appreciate whichever logo you're going to use. 

Thank you. 😊

**Comment by EmmanuelBeziat** [comment]
Hi,

Okay, it's done. Unfortunately, the `.pp` extension was already used for puphpet… I tried to define a workspace type (pascal) so the cheetah icon would be used for it in this case, but I'm not sure it's gonna work.

Check out the new version!
Thanks!

**Comment by pakLebah** [comment]
Update the extension, reload, restart VS Code. And… nope, it doesn't work. Screenshot attached.

![vs_code_icons_pascal](https://user-images.githubusercontent.com/11470932/37580279-7682af0e-2b75-11e8-9ccc-452f26d13b70.png)

**Comment by pakLebah** [comment]
Hi again… 

After I published in Pascal forum that your extension supports Pascal files, many of my fellow Pascal programmers install your extension. However, many of them said the icon of Pascal –the cheetah's head– is too "complicated" so it doesn't easily recognizable. Some people trying to make better icons, and I think the icon below would look better. 

Could you use this icon in your extension, please? If you could make it better, we'd be very grateful. Thank you. 😊 

Here's the proposal for new Pascal icon:
![pascal_logo_noshadow](https://user-images.githubusercontent.com/11470932/38123102-8870e8de-3403-11e8-8050-d60e2f9f1c5c.png)

**Comment by EmmanuelBeziat** [comment]
Hi,

It’s done! Let me know if it's better now. I hope this icon will be okay, it might have way too much details for a 24x24 icon size…
