### ISSUE TITLE
Add Support file icons Terraform

### ISSUE THREAD

**Issue by petit-lu** [EmmanuelBeziat/vscode-great-icons#104]
Please add,
## Format to support

* [Type : terraform files ](https://www.terraform.io/)
* Official icon (https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2DGnn61GIhLXEVIL__uL0FbhOu1dEAgNyBfUvHb8e137Lvvvt)
* Files extensions: *.tf, *.tfvars

Thanks you a lot.

**Comment by EmmanuelBeziat** [comment]
Hi, 

It's done. Check out the new version :)
