### ISSUE TITLE
.rst icon support

### ISSUE THREAD

**Issue by grafa** [EmmanuelBeziat/vscode-great-icons#107]
## Format to support

* [.rst](https://en.wikipedia.org/wiki/ReStructuredText)
* Official icon - I don't think there is one.
* Files extensions: .rst

RST is heavily used by Python guys in terms of writing docs. The main tool Sphinx is build on top of RST.

Thank you

**Comment by EmmanuelBeziat** [comment]
Hi!

It's done. Check out the new v2.1.32!

Thanks for helping improving VSCode Great Icons!

**Comment by grafa** [comment]
Simply amazing! Thanks a lot.
