### ISSUE TITLE
tslint icon

### ISSUE THREAD

**Issue by CKGrafico** [EmmanuelBeziat/vscode-great-icons#108]
## Format to support

* [Type of file](https://palantir.github.io/tslint/usage/tslint-json/)
* Official icon (https://www.google.es/search?biw=1920&bih=949&tbm=isch&sa=1&ei=xBPrWqr8L-nZgAaHsoiQCw&q=typescript+icon&oq=typescript+icon&gs_l=psy-ab.3..0i19k1.2457.3539.0.3643.10.9.0.0.0.0.151.921.5j4.9.0....0...1c.1.64.psy-ab..4.6.623...0j0i7i30k1j0i7i10i30k1j0i7i30i19k1j0i5i30i19k1j0i8i30i19k1j0i13i5i30i19k1j0i8i13i30i19k1.0.ODGXSUOzEOM)

* Specific files names: tslint.json

**Comment by EmmanuelBeziat** [comment]
Hi!

It's done. Check out the new v2.1.32!

Thanks for helping improving VSCode Great Icons!
