### ISSUE TITLE
yaml/yml icon

### ISSUE THREAD

**Issue by FriedCircuits** [EmmanuelBeziat/vscode-great-icons#109]
## Format to support
* Official icon (existing .yaml icon)
* Files extensions: *.yml

It looks like this was fixed before but I just installed this and .yml doesn't show the icon that .yaml shows. Instead it has the default red {} icon.

Otherwise great set.

Thanks.

**Comment by EmmanuelBeziat** [comment]
Hi

This is weird… The yml has the right icon set. When I try, I have the right one too.

But it has happened before; last time, removing and reinstalling the plugin did the trick. Try this and tell me if it's still happening.

**Comment by FriedCircuits** [comment]
Hmm, nothing seems to work, tried reinstalling a few times. I have the same problem at work and at home.

**Comment by EmmanuelBeziat** [comment]
Let's see after this new update… But I tried again, and I have the icons Matching for yml and yaml files, both on macOS and Windows, on different pcs, and even different versions of the plugin… At this point, I really don't know why it won't work on yours… Sorry :(

**Comment by codyjohn** [comment]
I am seeing the same issue.  Just did my first install of the pack on Mac, version 2.1.35, and I'm seeing the default red icon for .yml files.

**Comment by FriedCircuits** [comment]
That is the one I am seeing as well. The example in the details shows a Y in a square for .yaml, which also shows the red curly braces if I rename to .yaml instead of .yml.

**Comment by EmmanuelBeziat** [comment]
Oh, then it's normal. The icon has been changed a few month ago, as it was a more common one that people recognized better.

As precised under the example, "this image is non-exhaustive and may not be up to date". I'll change it soon so people don't get confused.
