### ISSUE TITLE
Add Icon for Handlebars (.hbs) file extension

### ISSUE THREAD

**Issue by elrickvm** [EmmanuelBeziat/vscode-great-icons#11]
## Handlebars file.

* [.hbs](http://handlebarsjs.com/)
* Official icon (http://devswag.com/products/handlebars-sticker)
* Files extensions: *.hbs
* Specific files names: file1.hbs, file2.hbs

**Comment by EmmanuelBeziat** [comment]
Hi,
Here ya go: v1.1.22 contains your handlebars icon for .hbs files.

Happy coding!

**Comment by elrickvm** [comment]
Thank you very much!!!
