### ISSUE TITLE
BuckleScript icon

### ISSUE THREAD

**Issue by mudrz** [EmmanuelBeziat/vscode-great-icons#110]
## Format to support
BuckleScript - OCaml compiler which emits JavaScript

* [BuckleScript config and lock](https://bucklescript.github.io)
* [Official icon](https://bucklescript.github.io/img/logos/bucklescript_small.svg)
* Specific files names: `bsconfig.json` and `.bsb.lock`

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the delay. Check out the new 2.1.33 version !

Thanks :)

**Comment by mudrz** [comment]
Nice 👍 , this is awesome, I sent a link to your plugin in the Reason community chat :)

**Comment by EmmanuelBeziat** [comment]
Many thanks!
