### ISSUE TITLE
Dockerfile icon for environment

### ISSUE THREAD

**Issue by ausir0726** [EmmanuelBeziat/vscode-great-icons#112]
Hello for long time no see,
Thanks the great icons with us for a long time !!

sometimes people define a Dockerfile with service name , but we can't get correct icon :D

![image](https://user-images.githubusercontent.com/7247064/40887922-878e2578-6782-11e8-8932-b931f584a003.png)

* Type of file
Dockerfile for environment , same as Dockerfile

* Official icon (link or image)
same asDockerfile

* Files extensions: *.ext1, *.ext2
maybe someone use nginx.Dockerfile
or use Dockerfile.nginx

**Comment by EmmanuelBeziat** [comment]
Hi :) 

I’ve added Docker as an environment, as there were already Dockerfile in it… Not sure if it's going to work? Check out the new version and tell me if it's working, otherwise I’ll manually add some extensions.

Thanks!

**Comment by ausir0726** [comment]
Helo ,

seems like [env].Dockerfile  working perfect !! 💯 

but Dockerfile.[env]  not working.

I prefer collect all [env].Dockerfile in folder , but , I know someone like use Dockerfile.[env]

:D

thanks .

**Comment by ausir0726** [comment]
Hi, @EmmanuelBeziat 

thanks  🤣 

It should be followed by VSCODE rules.
I don't understand VSCODE plugin develope right now. If I see some useful information I will let you know.

thank you for everything.  👍
