### ISSUE TITLE
VSCode Great Icons does not obey user set file type for mustache

### ISSUE THREAD

**Issue by planigan** [EmmanuelBeziat/vscode-great-icons#115]
I really love this icon set, however, I am working on a meteor project that does not support naming spacebars/handlebars/mustache naming. In meteor, the templates must be named with a `.html` file extension. The workaround we have introduced to get proper syntax highlighting is to name templates with a `.hbs.html` extension and set that extension as mustache in VSCode. The built in icon themes recognize this. This theme is still displaying the html icon for them. 

I love this theme and really want to use it. Let me know if you need any clarification.

**Comment by planigan** [comment]
The built-in icon theme I am using the works as expected is `VSCode Icons`.

**Comment by planigan** [comment]
Relevent VSCode setting:

```
"files.associations": {
        "*.hbs.html": "handlebars"
    }
```

**Comment by planigan** [comment]
It looks like the Icon theme I am using is not built-in. I must have forgotten installing it. This is it: https://github.com/vscode-icons/vscode-icons

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay.

As strange as it is, the plugin should already have handled this case… I didn’t found anything useful in vscode icons yet, so I've added a specific file association to match your example so you don't have to wait too long.

**Comment by planigan** [comment]
Thank you! The new icon theme looks great! Love it!
