### ISSUE TITLE
Icon for Axure RP

### ISSUE THREAD

**Issue by DukeSammael** [EmmanuelBeziat/vscode-great-icons#116]
## Axure RP

* [Axure RP wireframe](https://www.axure.com/)
* https://d2v8ggac1o0f6z.cloudfront.net/gsc/JN1XRN/b7/31/f3/b731f3fd13a8408ab2f76259252b26fa/images/prototypes__specifications__and_diagrams_in_one_to/rpicon_u5.png
* *.rp

**Comment by EmmanuelBeziat** [comment]
Hi,

It's done, check out the new plugin version :)

**Comment by DukeSammael** [comment]
It looks great, thank you! :)
