### ISSUE TITLE
ICON for  .YML 

### ISSUE THREAD

**Issue by john-fletcher** [EmmanuelBeziat/vscode-great-icons#117]
YML

* YAML and YML files are one and the same. can you add the same icon for YML as well.

**Comment by EmmanuelBeziat** [comment]
Hi,

That's already the case:

![p0qbz_test yml cite fabrique 2018-07-25 21-20-22](https://user-images.githubusercontent.com/6781337/43222500-9944c0aa-9050-11e8-8b1b-2f5af26cf26f.jpg)

It seems you’re having the same bug as #109 

Very weird. Please check the comments in there, see if you can find any matching case with the other user, so I can identify why this happen…

Thanks

**Comment by john-fletcher** [comment]
Thanks. I was looking for the below image and thought "Y" would be for .yaml. its my mistake. 
![image](https://user-images.githubusercontent.com/17179026/43226115-87a375a8-9078-11e8-840f-f55b4c3616d6.png)

**Comment by EmmanuelBeziat** [comment]
Oh, okay.
I'll definitely update this image soon :)

**Comment by john-fletcher** [comment]
Thanks much!
