### ISSUE TITLE
Icons won't load since v2.1.37

### ISSUE THREAD

**Issue by Kalus** [EmmanuelBeziat/vscode-great-icons#118]
Hi,

Apologies for not being able to document this very well, but since the July 18th update I've been able to use VSCode Great Icons. When I choose the icon set, it previews and then displays the previously used icon set instead, or the default one.

Thanks,
Lukas

**Comment by EmmanuelBeziat** [comment]
Hi,

That's very strange… Have you tried to remove it then reinstall it? It's pretty basic but I've seen many strange problems being solved by this solution.

**Comment by Kalus** [comment]
Yes I have—a few times. I've also tried disabling every other extension,
and I've restarted the entire computer as well just in case.

**Comment by chrise86** [comment]
Also facing this issue.

**Comment by Elfayer** [comment]
Same here

**Comment by Elfayer** [comment]
I had vscode v.1.12.x, updated to 1.25, now works!

**Comment by chrise86** [comment]
@Elfayer `1.23.1` is the latest I can see, which is what I'm using

**Comment by Elfayer** [comment]
@chrise86 It's not the last version: https://code.visualstudio.com/updates/v1_25
You just do not get pinged on your vscode (as I wasn't pinged either), I had to install it manually, from the website: https://code.visualstudio.com/

![image](https://user-images.githubusercontent.com/15869149/43393796-f09736b6-942a-11e8-87b8-1fc3f6ace80b.png)

**Comment by chrise86** [comment]
@Elfayer manually updating fixed for me, thanks very much!

**Comment by Kalus** [comment]
Thanks @Elfayer, this worked perfectly! I was on 1.24.1.

**Comment by EmmanuelBeziat** [comment]
That's very strange anyway, it's totally supposed to work even on way earlier versions…

Well, glad to know it's solved for you anyway. :)
