### ISSUE TITLE
You can change 'How to use'

### ISSUE THREAD

**Issue by q962** [EmmanuelBeziat/vscode-great-icons#119]
No content you describe.
Make me confused.
I am looking for it but can't find it.
Later using the search only found one correlation. 
It asks me to modify the user settings and add '"workbench.iconTheme": "vscode-great-icons"'

**Comment by q962** [comment]
Describe it clearly

**Comment by EmmanuelBeziat** [comment]
Hi, 

I don't see how to make it more clear. It's already as simple as possible: "go to `settings`, then click on `Icon theme`, and finally choose the icon theme you want to use.

![capture d ecran 2018-08-07 a 15 16 02](https://user-images.githubusercontent.com/6781337/43778030-d9ee2728-9a54-11e8-9d42-cd3c1f4b0edd.jpg)

![capture d ecran 2018-08-07 a 15 16 11](https://user-images.githubusercontent.com/6781337/43778036-de590b3e-9a54-11e8-8b4b-c12fae9a1f6a.jpg)

**Comment by q962** [comment]
Ok, I understand the error, I understand the files in the settings.
sorry

**Comment by EmmanuelBeziat** [comment]
No problem :) Glad to help you!
