### ISSUE TITLE
Please add laravel blade icon

### ISSUE THREAD

**Issue by jurgentreep** [EmmanuelBeziat/vscode-great-icons#12]
I already looked for some icon but can't really find a good one. I hope you have more luck :)

[This one](https://www.iconfinder.com/icons/1006880/coding_development_js_laravel_logo_icon#size=128) might work but it doesn't really follow the other icons.

**Comment by EmmanuelBeziat** [comment]
Hi,
There's a blade icon already: 

![](https://images.emmanuelbeziat.com/Microsoft_Edge-ngb2i-fqm9j.jpg)

If you don't see it with the *.blade.php extension, let me know :)

**Comment by jurgentreep** [comment]
![screenshot](http://i.imgur.com/E9QqRpK.png)

It's not showing up for me.

**Comment by EmmanuelBeziat** [comment]
It seems you don’t see any icon, as your folders doesn't show up… ?

Make sure the icon set is active in Préférences → Icons Set.

Also, try to remove and reinstall the icon pack, then active it again.

**Comment by jurgentreep** [comment]
Reinstalling fixed it thanks :)

**Comment by EmmanuelBeziat** [comment]
Perfect. :)
