### ISSUE TITLE
D Programming Language

### ISSUE THREAD

**Issue by 0xEAB** [EmmanuelBeziat/vscode-great-icons#121]
## D Programming Language

* [D source code file](https://dlang.org)
* <img src="https://dlang.org/images/dlogo.svg" alt="d logo"/>
* <img src="https://dlang.org/favicon.ico" alt="d favicon"/>
* Files extensions: *.d, *.di
* Specific files names: dub.json ([DUB](https://code.dlang.org/) package file)

**Comment by 0xEAB** [comment]
Since the D logo looks aweful when scaled down, @WebFreak001 suggested to use the DConf logo instead: https://github.com/dlang-community/artwork/blob/master/logo_transparent/logo.svg

Preview: 
![logo_128](https://user-images.githubusercontent.com/15967408/44039243-fbf36b62-9f18-11e8-96f6-961b23523c03.png)

**Comment by WebFreak001** [comment]
it's the new not-yet-official logo, rebrand will happen eventually soon

**Comment by EmmanuelBeziat** [comment]
Hi,

Okay, it's added. Check out the new v2.1.40, and tell me if it suits you. The new logo still has many details, I’m not sure it would be clear enough on a 24x24 icon.

**Comment by 0xEAB** [comment]
That was quite quick, thanks :+1: 
in my opinion it looks fine
