### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by DavidBabel** [EmmanuelBeziat/vscode-great-icons#124]
Hey there, just updated my fork with your updates, pretty good work.

If you are interested to take a look at my changes it's here : 
https://github.com/DavidBabel/vscode-simpler-icons/pull/10/commits/c5115f951734f6bed2b089a46949a9da1739ff40

May inspire you !

Bye

**Comment by EmmanuelBeziat** [comment]
Hi,

Glad to see that you version is making it's way :) I’ll add a link to your set for angular people, or some who’d prefer a simpler set for various preprocessors.

**Comment by DavidBabel** [comment]
Oh thanks, actually i did this version because i liked your theme but want to customize it a bit.
I released it for my team because we work with angular. I have no real credit on it ^^

**Comment by EmmanuelBeziat** [comment]
Hi,

I added a link to your fork in the readme :)

**Comment by DavidBabel** [comment]
Damn, i will have to maintain it ^^ . Thanks
