### ISSUE TITLE
Additional MSBuild-related file extensions

### ISSUE THREAD

**Issue by seraku24** [EmmanuelBeziat/vscode-great-icons#125]
A general Visual Studio icon already exists for C# and F# projects (`.csproj` and `.fsproj`).  Would it be possible to map the same icon (or something suitable) to the other MSBuild-related files?

- MSBuild files
  - Generic file, `.msbuild`
  - Properties file, `.props`
  - Targets file, `.targets`
- MSBuild projects (current)
  - Generic project, `.proj`
  - JavaScript project, `.jsproj`
  - SQL database project, `.sqlproj`
  - VB project, `.vbproj`
  - C/C++ project, `.vcxproj`
  - Windows Installer project, `.wixproj`
- MSBuild projects (legacy)
  - Database project, `.dbproj`
  - LightSwitch project, `.lsproj`
  - UML project, `.modelproj`
  - C/C++ project, `.vcproj`
  - Windows Web Application project, `.wwaproj`

NOTE: MSBuild does have [official branding](https://github.com/Microsoft/msbuild/tree/master/branding).  Although to be honest, I think I prefer the simple, geometric icon for Visual Studio.  If you are feeling particularly creative, perhaps you can find a way to adapt the official icon.

Also NOTE: Technically, MSBuild will open *any* file ending in `proj`, but I am doubtful whether it would a good idea to assign its icon to all such files.  As such, it is my intention to try to provide as complete a list as possible, although I cannot claim this is definitive.  Of note, I have categorized projects that are now legacy, that is files no longer supported/generated by the current version of Visual Studio.  These files might still appear in the wild, but I suspect they are less likely to be relevant for folks using Visual Studio Code.

**Comment by EmmanuelBeziat** [comment]
Hi!

Okay, I’ll check on this. Though, I fear `.props` might be a bit generic, I’ll have to double check if it's not used somewhere else. If so, I’ll try to have a compromise.

What would you thing of having 3 icons types for this list? One for build files, one for build projects, and one for legacy build projects ?

I'm not using MDBuilds, so I don't know if that would be enough to have a good view over a project?

**Comment by seraku24** [comment]
Regarding things like `.props` that could have collisions with other file types, perhaps the solution is to map them to a slightly more general icon rather than being MSBuild-specific.  At a minimum, the file would not use the plain icon and can stand out a bit, but it can also fit multiple roles.  Granted, it would be nice for all of the MSBuild files to feel like they belong together and have a unique visual identity like other build systems (e.g. CMake), so there is obviously a careful balance to strike.

To your question about multiple icons... Distinguishing the properties/targets files from projects could be useful.  However, I am not certain it is as important to distinguish between current and legacy project types in particular *unless* we wanted to go as far as giving each individual project something unique.  Visual Studio, for instance, uses fairly similar icons for projects but overlays text, such as "C#", or shapes, such as a cylinder for databases, to call out the differences.  But that feels like a lot of pixel work for arguably little gain.  Color/palette swaps could of course be easier, but then that leaves out our colorblind brethren.

**Comment by EmmanuelBeziat** [comment]
Hi,

Check out the new v2.1.42 :)
