### ISSUE TITLE
Would it be possible to suport Dockerfile icon for "Dockerfile.*" ?

### ISSUE THREAD

**Issue by Szauka** [EmmanuelBeziat/vscode-great-icons#126]
## Format to support

Would it be possible to suport Dockerfile icon for ```Dockerfile.dev, Dockerfile.*``` ?
And the same for docker-compose.yml (```docker-compose.dev.yml, docker-compose.*.yml ```) ?

**Comment by EmmanuelBeziat** [comment]
Hi,

At the moment it don't seem possible to add any "predictive" instruction. I can only define extensions or full file names, so I could do `Dockerfile.dev` and `docker-compose.dev.yml` as your examples, but not the other ones :/

If you have any example of some icon set allowing this, please give me a link so I could check out how it's done.

In the meantime, give me the filenames that you would need the most (like `Dockerfile.dev` and `docker-compose.dev.yml`) and I will add them :)

**Comment by Szauka** [comment]
Hi, 

I had a quick look around to see if I can find something and I found this settings https://github.com/Microsoft/vscode-docker/issues/192#issuecomment-353517815

It does bring back the icon for Dockerfile* but not for docker-compose*, but it looks like there is an issue with VS Code itself for the docker-compose* icon so not sure if anything could be done from tis extension.

**Comment by EmmanuelBeziat** [comment]
Thanks for your investigation, i’ll check it quickly.

**Comment by EmmanuelBeziat** [comment]
Hi,

Check out the new v2.1.42 :)
