### ISSUE TITLE
Different icon for .java and .class files

### ISSUE THREAD

**Issue by Splike** [EmmanuelBeziat/vscode-great-icons#129]
Currently `.java` and `.class` files share the same icon. It would be great if they had different icons.

**Comment by EmmanuelBeziat** [comment]
Hi,

That's weird, the `.class` extension isn’t currently handled… Can you provide a specific example? Is it a full file name?

Also, which icon would be relevant in your opinion?

Thanks!

**Comment by Splike** [comment]
Using VSCode Great Icons, `.java` and `.class` files have the following purple icon:
![image](https://user-images.githubusercontent.com/7159527/46584284-e9ec0e00-ca61-11e8-8f13-081528d5cd7f.png)

Using the Seti icon theme that comes with VSCode, the files have the following red icon:
![image](https://user-images.githubusercontent.com/7159527/46584301-012afb80-ca62-11e8-94c9-925bfa70cf90.png)

I noticed that the purple java icon is very low quality compared to the red one.

**My suggestion**
- Update the purple icon to the same quality level as the red.
- Use the red icon for `.java` files
- Use the purple icon for `.class` files

**Comment by EmmanuelBeziat** [comment]
Hi,
Check out the new 2.1.45 version!

**Comment by Splike** [comment]
Perfect! Thank you so much!
