### ISSUE TITLE
test icon request

### ISSUE THREAD

**Issue by zawiasam** [EmmanuelBeziat/vscode-great-icons#13]
## Format to support
could you please prepare some test icons ?

* Files extensions: *.test.js, *.spec.js
* Specific directory/folder names: test, __tests__, __mocks__

**Comment by EmmanuelBeziat** [comment]
Hi,
There are some for Mocha and Karma. I can add some more generic ones for those file formats and folders. I’ll do this asap.

**Comment by zawiasam** [comment]
Great! I found in other pack such icon, but I think it would be better to use other color (maybe not all elements of icon)
![image](https://cloud.githubusercontent.com/assets/7436990/20474012/90477376-afc4-11e6-9dd7-33871beb328f.png)

**Comment by EmmanuelBeziat** [comment]
I like the Idea, I’ll figure out something

**Comment by EmmanuelBeziat** [comment]
Hi,

Ready in the next release, coming up soon.
