### ISSUE TITLE
Remove border/outline from purple Visual Studio icon.

### ISSUE THREAD

**Issue by seraku24** [EmmanuelBeziat/vscode-great-icons#130]
It seems most of the icons in this pack omit borders/outlining.  The purple Visual Studio icon has a white border that doesn't scale very well and looks off when using a dark theme.

![image](https://user-images.githubusercontent.com/20533271/45711441-70d25880-bb3e-11e8-9b1d-70e0dcbcfdcc.png)

Looking at the other icons, I see that the blue Visual Studio Code icon has two versions, one with a white outline and one without.  Would it be possible to achieve the same for the purple version?

Note that this would affect the recently supported MSBuild file types (#125).

**Comment by EmmanuelBeziat** [comment]
Hi,

Check out the new version, the icons have been corrected. :) Thanks!
