### ISSUE TITLE
C++ header, additional extension

### ISSUE THREAD

**Issue by seraku24** [EmmanuelBeziat/vscode-great-icons#131]
`.hh` is another common file extension for C++ headers, which mimics `.cc` for C++ sources.

**Comment by EmmanuelBeziat** [comment]
Hi,
Check out the new 2.1.45 version!

**Comment by seraku24** [comment]
Thanks, although I suspect I misled you with my comment.  The intention is that `.hh` is a header file, so it should share the icon with `.hpp`.

What I had meant originally is that `.cc` and `.hh` form a common naming convention pair, not that they refer to the same type of file.  This is similar to the pairs of `.cpp`/`.hpp`, `.cxx`/`.hxx`, and `.C`/`.H`.  Granted, the last convention is only viable with a case-sensitive file system.

**Comment by EmmanuelBeziat** [comment]
Okay, it has been fixed :) Thanks!
