### ISSUE TITLE
Add LiveScript icon

### ISSUE THREAD

**Issue by alexteg-advisa** [EmmanuelBeziat/vscode-great-icons#132]
## LiveScript

* [LiveScript](http://livescript.net/)
* Official icon: [LiveScript logo](https://github.com/gkz/LiveScript/blob/master/logo.png)
  I'd suggest to use the icon part: 
![image](https://user-images.githubusercontent.com/18527849/47709023-b864fd80-dc2f-11e8-98f2-f3aa2c6143f2.png)
* Files extensions: `*.ls`

**Comment by EmmanuelBeziat** [comment]
Hi,
Check out the new 2.1.45 version!

**Comment by alexteg-advisa** [comment]
Amazing! Thanks!
