### ISSUE TITLE
Add .yml to .yaml icon

### ISSUE THREAD

**Issue by LeraAtwater** [EmmanuelBeziat/vscode-great-icons#133]
## Format to support

You currently have an appropriate icon for yaml files. However, it's only set to support the .yaml extension. Could the .yml extension also be set to that icon? This is the extension used across Drupal, which I work in. We have, no exaggeration, thousands of .yml files.

Thanks for your great efforts!

**Comment by EmmanuelBeziat** [comment]
Hi,

I think this is the same problem as #117  ?

**Comment by LeraAtwater** [comment]
Oh, I see the same request. So there is no Y for yaml like in the image? Currently I have the generic {...} for .yml and thought we may  be able to use the Y in a box like in the image.

If that's not the plan, okay, I did like the Y though.
