### ISSUE TITLE
Add more icons

### ISSUE THREAD

**Issue by SigmundurMorkore** [EmmanuelBeziat/vscode-great-icons#136]
Would it be possible to add icons to these files? Most of these files would use icons that are already associated with other files.

## More .env files
* .env.production
* .env.development
* .env.example

## More webpack files
* webpack.config.base.js

## More jest files
* jest.config.js

## Possible Docz support?
Logo: https://www.docz.site/static/img/logo.4f4f7bc5.svg
File: doczrc.js

**Comment by EmmanuelBeziat** [comment]
Hi, I merged your PR, I'll add jest icon and doczrc asap. :) Thanks

**Comment by SigmundurMorkore** [comment]
Awesome! Thank you :)

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the delay. It's all in the new 2.1.47 version, check it out! :)

**Comment by SigmundurMorkore** [comment]
Looks great! :D
