### ISSUE TITLE
Can the `.tsx` and `.jsx` files not have the same icon?

### ISSUE THREAD

**Issue by ddzy** [EmmanuelBeziat/vscode-great-icons#140]
## Feature Request

The same as title,  I think if the two can be distinguished, it will be better.
![vsce_issue_1](https://user-images.githubusercontent.com/33921398/52171263-dabd6880-2794-11e9-986d-31a5e1298f08.jpg)

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the delay. It's all in the new 2.1.47 version, check it out! :)

**Comment by ddzy** [comment]
> Hi,
> 
> Sorry for the delay. It's all in the new 2.1.47 version, check it out! :)

Looks great!
