### ISSUE TITLE
Prisma datamodel icon support

### ISSUE THREAD

**Issue by vaunus** [EmmanuelBeziat/vscode-great-icons#142]
## Format to support
Please could support for Prisma datamodel files be added:

* [Prisma datamodel files](https://www.prisma.io/). See also the [docs](https://www.prisma.io/docs/datamodel-and-migrations/datamodel-MYSQL-knul/#files) which refer to the usage of these *.prisma files
* Official icon (https://camo.githubusercontent.com/c7f49c483a3c5a145ff55c7331520a65e12abff2/68747470733a2f2f692e696d6775722e636f6d2f774434725674342e706e67)
* Files extensions: *.prisma
* Specific files names: N/A

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the delay. It's all in the new 2.1.47 version, check it out! :)

**Comment by vaunus** [comment]
Looks awesome - thank you so much! 😄
