### ISSUE TITLE
Support for TOML files

### ISSUE THREAD

**Issue by KorayGocmen** [EmmanuelBeziat/vscode-great-icons#143]
## Support for TOML

* [TOML](https://github.com/toml-lang/toml) 
* https://raw.githubusercontent.com/toml-lang/toml/master/logos/toml-100.png
* Files extensions: .toml
* Specific files names: (if required; for example: gulpfile.js)  @.toml

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the delay. It's all in the new 2.1.47 version, check it out! :)
