### ISSUE TITLE
Support storybook files

### ISSUE THREAD

**Issue by ColCh** [EmmanuelBeziat/vscode-great-icons#144]
## Format to support

* [Storybook story](https://storybook.js.org/)
* Official icon [Favicon](https://storybook.js.org/static/storybook-icon.ddf01037.png). [vscode-icons uses it](https://github.com/vscode-icons/vscode-icons/blob/1a4a7339e3b46bc131bc0121284129f400f8a4fd/icons/file_type_storybook.svg)
* Files extensions: `*.story.js, *.story.jsx, *.story.ts, *.story.tsx`
* Specific files names: all inside `.storybook` dir? (not sure about this one). I suppose there is no specific file names

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the delay. It's all in the new 2.1.47 version, check it out! :)
