### ISSUE TITLE
Add icon for build folder.

### ISSUE THREAD

**Issue by pakLebah** [EmmanuelBeziat/vscode-great-icons#146]
## Build Folder

* Type: common folder for build target.
* Official icon: no official icon.
* Files extensions: it's a folder without extension.
* Specific folder names: `build`, `out`, `.build`, `.out`.

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay; I encounter problems with the extension, as it seems I've reach a file number limit. It need to be set as an extension package now, but for this I need to completely rebuild the extension.

Your request will be included at the same time.

Sorry again!

**Comment by EmmanuelBeziat** [comment]
@pakLebah okay, it's done. Check the new 2.1.53 version, and let me know if it suits you!

**Comment by pakLebah** [comment]
Thank you! 👍
