### ISSUE TITLE
Retina/High DPI display support?

### ISSUE THREAD

**Issue by atomiks** [EmmanuelBeziat/vscode-great-icons#147]
The icons appear low quality on high DPI displays 😢 

Apart from that this is easily the best pack I've found!

**Comment by EmmanuelBeziat** [comment]
Hi,

Do you have a reference for a specific screen where I could see that? I'm using a MacBook with Retina display and I don't seem to have this issue.

But in anycase, I could easily use higher res icons (I thought about SVG too, I'll have to decide). It would take a bit of time though… Sorry for that.

**Comment by atomiks** [comment]
Default icons

<img src="https://i.gyazo.com/d3b6a68f38bac7dd833e7cd12223586a.png" height="385" />

VSCode great icons

<img src="https://i.gyazo.com/f3574c0b578aaf5e98a8a6d19578ac22.png" height="385" />

**Comment by EmmanuelBeziat** [comment]
I see, it's stubtle but definitely there.

I’ll handle this asap, hang on :)

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay; I encounter problems with the extension, as it seems I've reach a file number limit. It need to be set as an extension package now, but for this I need to completely rebuild the extension.

Your request will be included at the same time.

Sorry again!

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry again; a few icons has been set to SVG, more to come soon. Thanks!
