### ISSUE TITLE
Phoenix LiveView .leex icon support

### ISSUE THREAD

**Issue by orthodoX** [EmmanuelBeziat/vscode-great-icons#148]
## Format to support

This is a very simple request. 🙂 A recent public release of `LiveView` library for Elixir's web framework Phoenix introduced a new template extension `.leex`. Basically all there is to be done is to set the same icon that is currently displayed for `.eex` files.

<img width="271" alt="Screen Shot 2019-04-14 at 21 57 30" src="https://user-images.githubusercontent.com/370935/56098408-9e2e8b80-5f00-11e9-980d-d878467c69fb.png">

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay; I encounter problems with the extension, as it seems I've reach a file number limit. It need to be set as an extension package now, but for this I need to completely rebuild the extension.

Your request will be included at the same time.

Sorry again!

**Comment by orthodoX** [comment]
Hi @EmmanuelBeziat Any news on this one? 🙂

**Comment by lbighetti** [comment]
Howdy! this is working now, you can close this issue! 🎉

**Comment by EmmanuelBeziat** [comment]
Sorry for the long delay, it's now fixed in the new 2.1.48 version
