### ISSUE TITLE
Support dotnet .razor files

### ISSUE THREAD

**Issue by Kinkyboo** [EmmanuelBeziat/vscode-great-icons#149]
Request support for .razor files introduced in asp.net Core 3.0

Icon can be found here [https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#razor](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#razor)

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay; I encounter problems with the extension, as it seems I've reach a file number limit. It need to be set as an extension package now, but for this I need to completely rebuild the extension.

Your request will be included at the same time.

Sorry again!

**Comment by EmmanuelBeziat** [comment]
Sorry for the long delay, it's now fixed in the new 2.1.48 version
