### ISSUE TITLE
New icon (.jinja .jinja2 .j2)

### ISSUE THREAD

**Issue by ghost** [EmmanuelBeziat/vscode-great-icons#150]
## Please add Jinja template icon

* [Jinja Templates](http://jinja.pocoo.org/docs/2.10/)
* Official icon (http://jinja.pocoo.org/docs/2.10/_static/jinja-small.png)
* Files extensions: *.j2, *.jinja2, *.jinja

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay; I encounter problems with the extension, as it seems I've reach a file number limit. It need to be set as an extension package now, but for this I need to completely rebuild the extension.

Your request will be included at the same time.

Sorry again!

**Comment by EmmanuelBeziat** [comment]
Sorry again for the VERY LONG delay. It's done! Check out the new 2.1.52 version.
Thanks!
