### ISSUE TITLE
Support .svelte template files

### ISSUE THREAD

**Issue by DaviSpindola** [EmmanuelBeziat/vscode-great-icons#152]
* [Svelte template](https://svelte.dev/)
* Files extensions: *.svelte
![svelte](https://svelte.dev/favicon.png)

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay; I encounter problems with the extension, as it seems I've reach a file number limit. It need to be set as an extension package now, but for this I need to completely rebuild the extension.

Your request will be included at the same time.

Sorry again!

**Comment by thismarcoantonio** [comment]
+1

**Comment by EmmanuelBeziat** [comment]
Sorry for the long delay, it's now fixed in the new 2.1.48 version
