### ISSUE TITLE
How to customize icons in this package?

### ISSUE THREAD

**Issue by iagobruno** [EmmanuelBeziat/vscode-great-icons#153]
Is there any way to customize the icons for a specific file type by changing something in the settings or swapping a file where the extension is installed? I searched the issues of this repo but found nothing related.
My perfectionism thanks in advance 😄 .

**Comment by EmmanuelBeziat** [comment]
Hi!

Sorry, but this package isn't evolved enough to allow customization… yet. I don't know when I'll have time and patience to do it. It's set for the future, but I can't say if it will be in a month or a year.

I'm totally okay to add or enhance icons myself if needed, though; but if you're in search of deep customization from your side, VSCode great icons might not be the best package for you.

Thanks anyway for your interest :)

**Comment by httpiago** [comment]
I know that vscode great icons allows customization, but I like more the icons of your package, it only has some specific icons that I wanted to change but ok.
