### ISSUE TITLE
Add Icon for .sequelizerc

### ISSUE THREAD

**Issue by armonkahil** [EmmanuelBeziat/vscode-great-icons#159]
## Format to support

* [.sequelizerc](https://sequelize.org/master/)
* https://sequelize.org/master/manual/asset/logo-small.png
* Files extensions: *.sequelizerc
* Specific files names: (if required; for example: gulpfile.js) file1.ext, file2.ext

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay. Check out the new 2.1.49 version!
