### ISSUE TITLE
Blue icons for react files (jsx/tsx)?

### ISSUE THREAD

**Issue by Xavi3RElvis** [EmmanuelBeziat/vscode-great-icons#161]
I love the icon set and the different coloring between jsx and tsx files,
but can you please change them both to different shades of blue?
this greenish shades are confusing for react projects,
especially since the official react colors are cyan/blue
and also the colors used by every other iconset

* Files extensions: *.tsx, *.jsx

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay. Check out the new 2.1.49 version!

**Comment by Xavi3RElvis** [comment]
Thank you for this!

**Comment by EmmanuelBeziat** [comment]
Let me know if you feel the color variation is not obvious enough.

**Comment by Xavi3RElvis** [comment]
This is beyond awesome, small suggestion is might need the color a bit lighter for a specific scenario:
![image](https://user-images.githubusercontent.com/16775752/91721840-13583a80-eba2-11ea-8291-1dcbf702acb8.png)
This is vscode default color scheme and on both light and dark default themes contrast is great with background, only on selected you have the file selected on the solution explorer you can see they sort of blend in.
A change to a lighter shade could help on this otherwise minor issue.
Thank you

**Comment by EmmanuelBeziat** [comment]
@Xavi3RElvis okay, it's done :) check the new 2.1.53 version!
