### ISSUE TITLE
Add icon for rdl (Report Definition Language) files.

### ISSUE THREAD

**Issue by michaeli99** [EmmanuelBeziat/vscode-great-icons#162]
## rdl (Report Definition Language)

* https://docs.microsoft.com/en-us/sql/reporting-services/reports/report-definition-language-ssrs?view=sql-server-ver15
* Official icon: Couldn't find one, so I just used what windows shows
* Files extensions: *.rdl

![2020-02-13 09_21_53-Window](https://user-images.githubusercontent.com/33363962/74449574-5d661280-4e42-11ea-933d-768dfb2ba7f4.png)

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay,
I added the logo from databases, is that okay for you? Check out the new version and let me know!

**Comment by michaeli99** [comment]
I do not have a problem with using the SQL icon.  99% of my RDL files are accessing a SQL database anyway.  Someone else might not like it down the road, but for now it is better than nothing.

**Comment by EmmanuelBeziat** [comment]
Okay, I'll decide what to do if the case comes out. Thanks for your help!
