### ISSUE TITLE
Reverse closed folder colors

### ISSUE THREAD

**Issue by ThomasTheDebugEngine** [EmmanuelBeziat/vscode-great-icons#163]
I find the folder icon when folder closed to be rather distracting Is it possible to reverse the folder open/closed colors so that the open folder would be the only folder "highlighted" ?

**Comment by EmmanuelBeziat** [comment]
Hi,

Not at the moment, but I'll try to add that someday!

**Comment by ThomasTheDebugEngine** [comment]
appreciate that, thanks
