### ISSUE TITLE
Racket and Scheme

### ISSUE THREAD

**Issue by seraku24** [EmmanuelBeziat/vscode-great-icons#165]
## Racket

* [Racket (official site)](https://racket-lang.org/)
* [Official icon (link, hosted on wikipedia)](https://en.wikipedia.org/wiki/Racket_\(programming_language\)#/media/File:Racket-logo.svg)
* Files extensions: `*.rkt`
* Specific files names: *none that I am aware of*

## Scheme

* [Scheme (wikipedia)](https://en.wikipedia.org/wiki/Scheme_\(programming_language\))
* [Official icon (link, hosted on wikipedia)](https://en.wikipedia.org/wiki/Scheme_\(programming_language\)#/media/File:Lambda_lc.svg)
* Files extensions: `*.scm` `*.sch` `*.ss`
* Specific files names: *none that I am aware of*

NOTE: It could make sense to use a shared icon for both Racket and Scheme, seeing as Racket (formerly known as PLT Scheme) is just a modern dialect. For comparison, the `vscode-scheme` extension covers Racket, so there is some precedence for unifying the languages.

**Comment by EmmanuelBeziat** [comment]
Hi,
Sorry for the long delay. Check out the new 1.1.50 version!

**Comment by seraku24** [comment]
Would it be possible to change the color of the Scheme Lambda to something other than black?  When using a dark theme, it blends in too much with the background:

![vscode-great-icons-scheme-color-issue png](https://user-images.githubusercontent.com/20533271/91274403-7c1f5d00-e733-11ea-84b9-e9d3cae9d73c.png)

(NOTE: These images were taken with the Ayu Mirage and Ayu Light themes.)

As shown above, the functional languages already cover a fairly wide range of hues, so it might not be possible for the color to be completely distinct.  Here are are just a few options I came up with:

![vscode-great-icons-scheme-color-issue-2 png](https://user-images.githubusercontent.com/20533271/91278677-614fe700-e739-11ea-89d6-c86f0bd6720f.png)

|Color|RGB (Hex)|Notes|
|---|---|---|
|Lavender|`#B151BB`|Roughly halfway between the red and blue colors of the Racket logo.|
|Goldenrod|`#EEC41B`|Closer to pure yellow compared to Haskell and OCaml.|
|Medium Grey|`#8C8C8C`|Achromatic option that should read well on both light and dark themes.|

That said, pick whatever color you think works best to fit in with the other icons in the pack.

**Comment by EmmanuelBeziat** [comment]
@seraku24 my bad, I'll change that quickly. Thanks for the warning!

**Comment by EmmanuelBeziat** [comment]
Okay, that's done. I went for lavender, think it's the better one for both dark and light versions!
Check out the new 2.1.52 version.
Thanks!
