### ISSUE TITLE
icon request for sketch & figma files

### ISSUE THREAD

**Issue by massimo-cassandro** [EmmanuelBeziat/vscode-great-icons#169]
## Bohemian Coding Sketch files

Sketch is a design tool largely used for prototyping

* Site: https://www.sketch.com/
* Official icon attached
* Files extensions: .sketch
* No Specific files names

![sktech icon](https://user-images.githubusercontent.com/1047169/81818416-4bbe0500-952e-11ea-9ae1-6d47f82dbcdb.png)
[sktech icon.svg.zip](https://github.com/EmmanuelBeziat/vscode-great-icons/files/4622183/sktech.icon.svg.zip)

## Figma

Figma is another prototyping design tool. It is manly used online, but files can be saved on 

* Site: https://www.figma.com/
* Official icon attached
* Files extensions: .fig
* No Specific files names

[figma icon.svg.zip](https://github.com/EmmanuelBeziat/vscode-great-icons/files/4622176/figma.icon.svg.zip)
![figma icon](https://user-images.githubusercontent.com/1047169/81818312-2b8e4600-952e-11ea-93be-8956c6e7c99e.png)

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay. Check out the new 2.1.49 version!
