### ISSUE TITLE
Need more Icon Support

### ISSUE THREAD

**Issue by parwat08** [EmmanuelBeziat/vscode-great-icons#17]
no icons support for SRC, BUILD, .VSCODE, Public, CSS, images, Views, Temp, data and support "folders" and files icons for .jshintrc, .Procfile, and many more...

**Comment by EmmanuelBeziat** [comment]
Hi,

I don't plan to have dozens of folders colors for any type possible; this is a set I made for my use in first place, and this is exactly why I didn't stick with Seti or other packs, and decided to make mine.

Maybe this isn’t the best icon set for your needs? I suggest you to try out [Seti](https://marketplace.visualstudio.com/items?itemName=TsumiNa.Seti-theme). If you wish, you can also make a fork, like [DavidBabel](https://github.com/DavidBabel/vscode-simpler-icons) did, to better fit his needs with angular and remove some icons.

I’ll add jshint and procfils though, thanks!

**Comment by parwat08** [comment]
your icon sets are perfect! it would be more perfect if you would add some specific folder icons

**Comment by EmmanuelBeziat** [comment]
I can add .vscode folder soon for a start. For some folders like build / src / public, i need a bit of time to find or make good icons.

But having icons on my images/css/etc. folders really don’t please me… And it’d be sad if the set I made don’t suit me.

It would be cool if we could define options for icons sets. Anyway, I think I could make a "Enhanced" version of the set, with many more icons. You’d just have to remove this plugin and take the enhanced version (and people could have choice of the version they need). Of course, if I update the standard version, the enhanced version would be equally updated.

What do you think about this ?

**Comment by parwat08** [comment]
This would be perfect, I will be expecting enhanced version soon then! but When?

**Comment by EmmanuelBeziat** [comment]
Less than a few days. I just need to make the icons. Can you provide me a more complete list of which folders and extension you feel are missing?

**Comment by parwat08** [comment]
Src, Build, Test, .VSCode,Public, CSS, images, Views, Temp, data and support FOLDERS..
and 
.txt, .jshintrc, Procfile

It would be best if you would add angular icons on .ts  like DavidBabel did for enhanced version 
and for standard version i think for .ts file the icon would better if only ts word is used like js icon, the current .ts square icon doesn't seem to be good looking, it's like an alien sitting around humans

**Comment by BillDenton** [comment]
Could you also C and C++ header files, .h and .hpp.

**Comment by Sloven** [comment]
I miss the icon for custom gulp folder. Something similar to bower_components or node_modules.

**Comment by mtnrbq** [comment]
Could you add support for .elm? Here is the [favicon](https://raw.githubusercontent.com/elm-lang/elm-lang.org/master/assets/favicon.ico) <img src="https://raw.githubusercontent.com/elm-lang/elm-lang.org/master/assets/favicon.ico" width="15" height="15" /> for Elm.
