### ISSUE TITLE
Icon request for Oracle MySQL Workbench

### ISSUE THREAD

**Issue by massimo-cassandro** [EmmanuelBeziat/vscode-great-icons#170]
## Oracle MySQL Workbench

* https://www.mysql.com/it/products/workbench/
* Official icon 
<img width="512" alt="wb" src="https://user-images.githubusercontent.com/1047169/81819311-72307000-952f-11ea-9781-a5c6e9a1c3a8.png">

* Files extensions: *.mwb, *.mwb.beforefix, *.mwb.bak
* No Specific files name

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay. Check out the new version!
