### ISSUE TITLE
Storybook icon broken

### ISSUE THREAD

**Issue by MariuzM** [EmmanuelBeziat/vscode-great-icons#174]
Storybook icon not showing 
<img width="367" alt="Screen Shot 2020-08-22 at 11 51 10" src="https://user-images.githubusercontent.com/36937039/90954643-d8515b00-e46d-11ea-8ab6-cc4dc4d3f0cb.png">

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the delay, it's now fixed in the new 2.1.48 version

**Comment by MariuzM** [comment]
Hm i still had that problem so again i've changed back to stories

**Comment by EmmanuelBeziat** [comment]
That's really weird… Just in case, have you tried to completely uninstall the extension, then reinstall it? It seems to have solved a few icons weird activity for other people.

Let me know if it worked. :)
