### ISSUE TITLE
Edit Jest Icon

### ISSUE THREAD

**Issue by MariuzM** [EmmanuelBeziat/vscode-great-icons#175]
I feel that with this update or maybe i have not noticed before but Jest icon is to big and to bright 
<img width="204" alt="Screen Shot 2020-08-26 at 11 45 34" src="https://user-images.githubusercontent.com/36937039/91294572-a869c680-e791-11ea-8bd2-fd83a3bfa960.png">

**Comment by EmmanuelBeziat** [comment]
Mmh, yeah, definitely. I'll change that quickly. Thanks!

**Comment by EmmanuelBeziat** [comment]
Okay, that's done. Check out the new 2.1.52 version.
Thanks!
