### ISSUE TITLE
Ruby file icons not showing

### ISSUE THREAD

**Issue by giansluca** [EmmanuelBeziat/vscode-great-icons#176]
<img width="287" alt="screen" src="https://user-images.githubusercontent.com/11060553/91332497-90fbff00-e7cc-11ea-909b-11e85d6eac87.png">

**Comment by EmmanuelBeziat** [comment]
Okay, that's done.
Check out the new 2.1.52 version.
Thanks!

**Comment by giansluca** [comment]
Yes, now is working !
