### ISSUE TITLE
ES6 --> JS 

### ISSUE THREAD

**Issue by kadza93** [EmmanuelBeziat/vscode-great-icons#18]
First of all thank you for your great work i appreciate it greatly.

So my issue is since i love to use .es6 naming my js and i don't like the default style or rather lack of style for .es6 icon i was wondering could you just make it so that .es6 extensions gets same icon as .js that would be awesome. Here is [link](http://svgporn.com/) to various svg icons that you may find helpful, note that there is svg for ES6 there so if you wish you can implement that, its a great source for icons.

Edit: Also you could improve use case scenarios for .eslint icon to support following

- JavaScript - use .eslintrc.js and export an object containing your configuration.
- YAML - use .eslintrc.yaml or .eslintrc.yml to define the configuration structure.
- JSON - use .eslintrc.json to define the configuration structure. ESLint’s JSON files also allow JavaScript-style comments.
- Deprecated - use .eslintrc, which can be either JSON or YAML.
- package.json - create an eslintConfig property in your package.json file and define your configuration there.

**Comment by EmmanuelBeziat** [comment]
It's done!
Thanks
