### ISSUE TITLE
Build folder icon is not displayed if only containing subfolders.

### ISSUE THREAD

**Issue by vetaltor** [EmmanuelBeziat/vscode-great-icons#180]
Hi. Thank you for this icon pack.
I have a 'ProjectName' folder under 'build' folder, and that's where all build artifacts go. And for now my build folder icon is a regular folder. The icon only changes when I place a file directly under 'build' folder.

**Comment by EmmanuelBeziat** [comment]
Hi, thanks for letting me know that.

It's a feature from vscode, who compact the folders when they are empty, which also, as a result, show the child folder's icon.

Here for example, the test folder's icon is shown:

![Code_HwmoW29ZUp](https://user-images.githubusercontent.com/6781337/93407558-cb6c2f80-f892-11ea-82f7-02d0e43079b5.jpg)

But here, it's the default folder : 

![Code_yCUdiZ69ys](https://user-images.githubusercontent.com/6781337/93407616-e474e080-f892-11ea-847e-72804e8011e5.jpg)

If you dislike it, you can disable this feature and it will show as this:

![Code_HOME8nLwEg](https://user-images.githubusercontent.com/6781337/93407664-fb1b3780-f892-11ea-8352-48f71671e34c.jpg)

Here's how you disable it: https://stackoverflow.com/questions/59415299/vscode-disable-empty-folders-merge-collapse

Here you go :)
