### ISSUE TITLE
Add .env.local icon

### ISSUE THREAD

**Issue by zmzhoi** [EmmanuelBeziat/vscode-great-icons#182]
![image](https://user-images.githubusercontent.com/71691394/95168475-51bdc680-07ec-11eb-8800-66a9f2307a8a.png)

**Comment by EmmanuelBeziat** [comment]
Hi! 

There you go! Check out the new v2.1.57 :)

**Comment by plaxcoder** [comment]
> Hi!
> 
> There you go! Check out the new v2.1.57 :)

wow wow wow thank you!

**Comment by zmzhoi** [comment]
> Hi!
> 
> There you go! Check out the new v2.1.57 :)

wow wow wow thank you so much!

> Hi!
> 
> There you go! Check out the new v2.1.57 :)

wow wow wow thank you so much!

**Comment by zmzhoi** [comment]
wow wow wow thank you so much!
