### ISSUE TITLE
ICON BUG . gitignore 中间如果有空格，依然会加载出icon图标

### ISSUE THREAD

**Issue by ddmy** [EmmanuelBeziat/vscode-great-icons#183]
version： 2.1.57
`. gitignore` 文件名`.`后面如果有一个空格： `. gitignore` 该文件会失去原本的作用，不应该正确初始化icon，应该给开发者一个友好的展示。

**Comment by EmmanuelBeziat** [comment]
Hi,

I don’t understand chinese, sorry; from what I get thanks to Google translate, you’re suggesting to allow a space after the dot?

```. gitignore```

instead of this ?

```.gitignore```

I never saw a project doing this? I don’t really get why?

**Comment by EmmanuelBeziat** [comment]
@ddmy done! Check out the new v2.1.58 ;)

**Comment by ddmy** [comment]
> @ddmy done! Check out the new v2.1.58 ;)
---
version: 2.1.58
Thanks, but now, 
`.gitignore`  Can’t display normally even if the name is correct

![image](https://user-images.githubusercontent.com/19168372/97105007-1b8cac00-16f3-11eb-9292-8310207265d6.png)
![image](https://user-images.githubusercontent.com/19168372/97105019-2f381280-16f3-11eb-94de-c52b85ce7e92.png)

**Comment by EmmanuelBeziat** [comment]
I have to roll back. It seems there is no ways to prevent any space between the dot and the filename. Every icon theme will allow ". gitignore" and any file extension with a space.
