### ISSUE TITLE
Add abelljs icon

### ISSUE THREAD

**Issue by harshhhdev** [EmmanuelBeziat/vscode-great-icons#188]
## Format to support

* [abelljs](https://abelljs.org)
* [Official icon](https://avatars0.githubusercontent.com/u/63695854?s=200&v=4)
* Files extensions: .abell

**Comment by EmmanuelBeziat** [comment]
Hi, thanks for your PR. It's now live in the new @2.1.63 version!

**Comment by harshhhdev** [comment]
![image](https://user-images.githubusercontent.com/69592270/103251626-6fac4a80-4947-11eb-84ce-252d49387978.png)

In the above image, it shows the icon is just blank @EmmanuelBeziat

**Comment by EmmanuelBeziat** [comment]
@harshhhdev Sorry about that. Just published a fix, check out the new @2.1.64 version. :)
