### ISSUE TITLE
Add new icon for the new Ruby type checking file

### ISSUE THREAD

**Issue by marcelobarreto** [EmmanuelBeziat/vscode-great-icons#190]
## Format to support

* [Type of file](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/)
* Official icon (?)
* Files extensions: *.rbs
* Specific files names: No

**Comment by EmmanuelBeziat** [comment]
Hi, thanks for your suggestion.

It's now live in the new @2.1.63 version!

**Comment by marcelobarreto** [comment]
Wow, that was fast, thanks @EmmanuelBeziat
