### ISSUE TITLE
webp images

### ISSUE THREAD

**Issue by RedGuy12** [EmmanuelBeziat/vscode-great-icons#192]
## Format to support

* [WebP](https://developers.google.com/speed/webp)
* Official icon (https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Johnrogershousemay2020.webp/300px-Johnrogershousemay2020.webp.png)
* .webp

**Comment by EmmanuelBeziat** [comment]
Hi,

Thanks for your suggestion and sorry for the long delay. This is added in the new 2.1.65 version, live now!
