### ISSUE TITLE
configuration files

### ISSUE THREAD

**Issue by RedGuy12** [EmmanuelBeziat/vscode-great-icons#194]
## Format to support

* Configuration file
* Official icon (https://upload.wikimedia.org/wikipedia/en/thumb/2/2f/INI_file_icon.png/64px-INI_file_icon.png)
* .conf, .ini, .load, .opt, .cnf

**Comment by EmmanuelBeziat** [comment]
Hi,

Thanks for your suggestion and sorry for the long delay. This is added in the new 2.1.65 version, live now!
