### ISSUE TITLE
sql files

### ISSUE THREAD

**Issue by RedGuy12** [EmmanuelBeziat/vscode-great-icons#195]
## SQL files:
.MYD
.MYI
.ibd
.trn
.mysql_history
.sql

icon: maybe something like https://cdn.freebiesupply.com/logos/large/2x/amazon-database-logo-png-transparent.png

**Comment by EmmanuelBeziat** [comment]
Hi,

Thanks for your suggestion and sorry for the long delay. This is added in the new 2.1.65 version, live now!
