### ISSUE TITLE
.log

### ISSUE THREAD

**Issue by RedGuy12** [EmmanuelBeziat/vscode-great-icons#196]
## Format to support

* log files
* icon: maybe like this?: https://media.istockphoto.com/vectors/history-icon-black-and-white-vector-sign-vector-id880471310?b=1&k=6&m=880471310&s=612x612&w=0&h=T8FKVpp-L6iNOkQ54jVYvCXRzSUmT09kGu4-Q7YUtW8=
* extensions: .log
* file names: error_log

**Comment by EmmanuelBeziat** [comment]
Hi,

Thanks for your suggestion and sorry for the long delay. This is added in the new 2.1.65 version, live now!
