### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by Aravindray** [EmmanuelBeziat/vscode-great-icons#197]
## Format to support

* [Type of file](https://www.arduino.cc/)
* Official icon (link or image)
* Files extensions: *.ino, *.ino
* Specific files names: (if required; for example: gulpfile.js) blink.ino

**Comment by EmmanuelBeziat** [comment]
Hi,

Thanks for your suggestion and sorry for the long delay. This is added in the new 2.1.65 version, live now!
