### ISSUE TITLE
browserlist

### ISSUE THREAD

**Issue by gorjiali** [EmmanuelBeziat/vscode-great-icons#199]
## Format to support

* [Type of file](https://github.com/browserslist/browserslist)
* [Official icon](https://camo.githubusercontent.com/bb6b4578e50ac6d75f11370ef609cd14b1d7b651c06773698316783e85215d32/68747470733a2f2f62726f77736572736c6973742e6769746875622e696f2f62726f77736572736c6973742f6c6f676f2e737667)
* Files extensions: .browserlistrc,

**Comment by EmmanuelBeziat** [comment]
Hi,

It's done, check the new v2.1.67!
