### ISSUE TITLE
README typo File -> Preferences

### ISSUE THREAD

**Issue by gregvanl** [EmmanuelBeziat/vscode-great-icons#2]
Just a typo in your extension README.  The File Icon Theme menu item is under Preferences not Settings.

**Comment by EmmanuelBeziat** [comment]
Okay, I'll correct this very soon. I don't have English version, so I assumed this one. Thanks!

**Comment by EmmanuelBeziat** [comment]
It's done. I also added a better preview image, and some badges. Thanks again!

**Comment by gregvanl** [comment]
Thanks. A nit: Next time you release you might make "file" with an uppercase "File" so it exactly matches the menu in the product.

**Comment by EmmanuelBeziat** [comment]
Thanks. I'm working on a better alignments for some of the icons, i'll put this with the next release (probably tonight).
