### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by crabicode** [EmmanuelBeziat/vscode-great-icons#20]
## Format to support

* [CSS stylesheets](http://postcss.org/)
* Official icon (http://postcss.org/_/web_modules/InANutshell/autoprefixer.svg)
* Files extensions: *.postcss, *.pcss

## Format to support

* [CSS stylesheets](http://postcss.org/)
* Official icon (https://camo.githubusercontent.com/38ffd496c4ce62f829d427bcdb3d172089674d54/687474703a2f2f706f73746373732e6769746875622e696f2f737567617273732f6c6f676f2e737667)
* Files extensions: *.sss

**Comment by EmmanuelBeziat** [comment]
Hi,
It's done. I couldn't find a good icon for sugarss that would be ok in such a small size, so i let postcss icon on it for now.
