### ISSUE TITLE
`benches` or `bench` folder icon

### ISSUE THREAD

**Issue by ok-nick** [EmmanuelBeziat/vscode-great-icons#203]
Add an icon for folders named `bench` or `benches`, which are typically used to store files for benchmarking code.

**Comment by UmairJibran** [comment]
Hey, @EmmanuelBeziat if you want you can resolve this issue.

**Comment by EmmanuelBeziat** [comment]
Hello @UmairJibran 

Don't worry, I'll adress this soon. :)

**Comment by EmmanuelBeziat** [comment]
Hi @ok-nick ;

Check out the new 2.1.74 version! Let me know if you have any issue with the new icon.

Thanks for helping improve vscode-great-icons!
