### ISSUE TITLE
Singularity Definition File Support

### ISSUE THREAD

**Issue by MillironX** [EmmanuelBeziat/vscode-great-icons#211]
## Format to support

* [Singularity](https://sylabs.io/singularity/) [Definition](https://sylabs.io/guides/3.8/user-guide/definition_files.html)
* Official icon
   ![Singularity Icon](https://raw.githack.com/sylabs/singularity/master/docs/logos/singularity_v3.svg)
   <https://github.com/sylabs/singularity/blob/master/docs/logos/singularity_v3.svg>
* Files extensions: *.def
* Specific files names: `Singularity` (case-sensitive: legacy definition filename)

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay. This is now added in the new 2.1.80 version. Be sure to try it and make feedback if needed, as VSCode don't make case-sensitive filenames detection on this case…

Thanks!
