### ISSUE TITLE
Fortran File Support

### ISSUE THREAD

**Issue by zoziha** [EmmanuelBeziat/vscode-great-icons#214]
## Format to support

* [Type of file: Fortran](https://fortran-lang.org/)
* Official icon (link or image): [fortran-logo.svg](https://github.com/fortran-lang/fortran-lang.org/blob/master/assets/img/fortran-logo.svg) or [fortran_logo_***.png](https://github.com/fortran-lang/fortran-lang.org/tree/master/assets/img)
* Files extensions: `*.f, *.for, *.f90, ... ; *.F, *.FOR, *.F90, ...` (with preprocessor)
* Specific files names: none
* More info:
This icon is the one used by the current Fortran community.
![image](https://user-images.githubusercontent.com/32035096/134118612-072c1230-4d0c-4745-9311-1d8fea174384.png)

## Links
[Support additional file extensions](https://github.com/fortran-lang/fpm/issues/250) 
[Updated Fortran Icon](https://github.com/vscode-icons/vscode-icons/issues/2832)
[fortran-lang.org](https://fortran-lang.org/)

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay. This is now added in the new 2.1.80 version.

Thanks!
