### ISSUE TITLE
Add folders variety

### ISSUE THREAD

**Issue by nesslopz** [EmmanuelBeziat/vscode-great-icons#216]
Hi there! this icons theme is awesome for files, but is it possible to add more variety for folders?

For example, components, routes, styles, images, something like that?
> Example from material-icon
> ![](https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/main/images/folderIcons.png)

Not too much like these ones only a few of important folders

**Comment by EmmanuelBeziat** [comment]
Hi!

There are a few of folder types already (vscode, git, tests, node, jest, build, bower, bench, root…). But these are "normalized" folders names.

Some like "views, "constant", "scripts", "theme", "event" seems really out of bounds here.

That said, I feel I could add a few more without harm. Which one do you think are missing? Are there some you really wish to get?
