### ISSUE TITLE
AsciiDoctor File Support

### ISSUE THREAD

**Issue by Mo-Gul** [EmmanuelBeziat/vscode-great-icons#218]
## AsciiDoctor

* Type of file: [AsciiDoctor](https://asciidoctor.org/)
* Official icon: [on "Brand" repository in "logo" and/or "logo/icon" folder(s)](https://github.com/asciidoctor/brand)
* Files extensions: *.adoc, *.asciidoc

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay. This is now added in the new 2.1.80 version.

Thanks!
