### ISSUE TITLE
Please add ASP (Active Server Pages) icon

### ISSUE THREAD

**Issue by mvlaran** [EmmanuelBeziat/vscode-great-icons#219]
## Format to support

* Classic ASP (Active Server Pages)
* Official icon (I Dont know what is the official icon/image)
* Files extensions: *.asp; *.asa
* web.config

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay. I ended up picking the .NET icon for it. This is now added in the new 2.1.80 version.

Thanks!

**Comment by mvlaran** [comment]
Thanks! I've already seen here after updating! Great!


Marcus Vinicius Laranjeira
***@***.*** ***@***.***>*
(011) 9 9449-7064
www.marcuslaranjeira.com


Em sex., 21 de jan. de 2022 às 20:36, Emmanuel Béziat <
***@***.***> escreveu:
