### ISSUE TITLE
Yarn icon for .lock files has white outline?

### ISSUE THREAD

**Issue by jlmakes** [EmmanuelBeziat/vscode-great-icons#22]
I know the official logo uses the blue cat in a blue circle, and thus uses a white outline to distinguish the cat shape... but without the blue circle behind it (specifically on dark themes), the white border looks out of place alongside the other icons in this awesome package.

I'm merely suggesting either exploring any of the following:
- Remove the white border
- Add the blue circle behind the cat to the icon
- Use the logotype ("yarn") instead

If PRs are welcome, I don't mind proposing a new yarn icon.

Cheers! 🍻

**Comment by EmmanuelBeziat** [comment]
Hi,
Thanks for your suggestion. I think I'll just remove the border, to keep the icon simple.

**Comment by EmmanuelBeziat** [comment]
It's done!

**Comment by jlmakes** [comment]
Looks great!
