### ISSUE TITLE
Add vim

### ISSUE THREAD

**Issue by theblobscp** [EmmanuelBeziat/vscode-great-icons#220]
## Add vim support

* [Vim](https://www.vim.org/)
* Official icon (https://www.vim.org/images/vim_shortcut.ico)
* Files extensions: *.vim
* Specific files names: .vimrc, .gvimrc

**Comment by EmmanuelBeziat** [comment]
Hi,

Sorry for the long delay. This is now added in the new 2.1.80 version.

Thanks!

**Comment by theblobscp** [comment]
Thank you!
