### ISSUE TITLE
Format to support for a file named Steepfile

### ISSUE THREAD

**Issue by koukikitamura** [EmmanuelBeziat/vscode-great-icons#221]
## Format to support
I want to an icon for a file named `Steepfile`. The `Steepfile` is [Steep](https://github.com/soutaro/steep)'s configuration file. The Steep is a Ruby library called [RubyGems](https://rubygems.org/) and a type checker for Ruby. Since version 3, Ruby officially provides the type definition language called [RBS](https://github.com/ruby/rbs). The extension of RBS is `.rbs`, and the relationship between `.rb` and `.rbs` is similar to the relationship between `.js` and `.d.ts` Steep checks type of a Ruby file based on an RBS file.

An icon for `*.rbs` has already been added.

* Official icon: An official icon is nothing. I propose that "Steepfile"'s icon should be a ruby official icon as well as "Gemfile".
* Files extensions: Nothing
* Specific files names: Steepfile

## Links
- [Ruby 3.0.0 released](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/)

**Comment by EmmanuelBeziat** [comment]
Hi @koukikitamura 

Check out the new version! Thanks :)
