### ISSUE TITLE
.htaccess icon too big

### ISSUE THREAD

**Issue by ChristianHecker** [EmmanuelBeziat/vscode-great-icons#226]
Hi there,
I love your icons.
Only the icon for .htaccess is cut off.
See screenshot.
<img width="286" alt="Bildschirmfoto" src="https://user-images.githubusercontent.com/78808318/157610334-00d1b6be-311a-461e-98fb-5bbbf7782354.png">

**Comment by EmmanuelBeziat** [comment]
Hi @ChristianHecker 

I fixed it, check out the new 2.1.85 version :)

Thanks!

**Comment by ChristianHecker** [comment]
Great that makes my day.

Thank you
