### ISSUE TITLE
Turborepo, Svelte Kit, Vitest, & Keystone Icons

### ISSUE THREAD

**Issue by codingwithchris** [EmmanuelBeziat/vscode-great-icons#229]
## Format to support

**Turborepo**
* [Website](https://turborepo.org/)
* [Official icon](https://turborepo.org/images/favicon/apple-touch-icon.png)
* Files extensions: `*.json`
* Specific files names: `turbo`

**Svelte Kit**
* [Website](https://kit.svelte.dev/)
* [Official icon](https://upload.wikimedia.org/wikipedia/commons/1/1b/Svelte_Logo.svg)
* Files extensions: `*.js`
* Specific files names: `svelte.config`

**Vitest**
* [Website](https://vitest.dev/)
* [Official icon](https://vitest.dev/logo.svg)
* Files extensions: `*.js`, `*.ts`
* Specific files names: `vitest.config`, `.vitest.config`

**Keystone JS**
* [Website](https://keystonejs.com/)
* [Official icon](https://keystonejs.com/branding)
* Files extensions: `*.ts`
* Specific files names: `keystone`

**Comment by EmmanuelBeziat** [comment]
Hi @codingwithchris 

I fixed it, check out the new 2.1.85 version :)

Thanks!

**Comment by codingwithchris** [comment]
@EmmanuelBeziat Some of the file name associations are incorrect for for the new icons :) I tried my best to specify the correct names above, but I'll list them out here!

**Vitest:**
These are the only officially supported extensions for vitest:
`vitest.config.js`
`vitest.config.ts`

**Turborepo:**
This is the only officially supported syntax for turborepo: `turbo.json` 

**Keystone**
`keystone.ts` is the only supported name for keystone configs currently.

**Comment by EmmanuelBeziat** [comment]
@codingwithchris okay, it should be fixed now! Thanks for the adjustments :)
