### ISSUE TITLE
Minor issue with reported version number

### ISSUE THREAD

**Issue by seraku24** [EmmanuelBeziat/vscode-great-icons#23]
I just installed the latest build which reports itself as version `1.1.27`.  However, after reviewing the changes to see what was added, I noticed that both the `README.md` and `CHANGELOG.md` files list the version as `1.2.27`.

**Comment by EmmanuelBeziat** [comment]
Woops!

Thanks for reporting this, I’ll fix this quickly.

**Comment by EmmanuelBeziat** [comment]
It's done :) Thanks again
