### ISSUE TITLE
.proto Have no icon

### ISSUE THREAD

**Issue by OmarOdaini** [EmmanuelBeziat/vscode-great-icons#230]
## Format to support
*.proto

* [Type of file](https://developers.google.com/protocol-buffers)
* Official icon (https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_protobuf.svg)
* Files extensions: *.proto
* Specific files names: (if required; for example: gulpfile.js) file1.ext, file2.ext

**Comment by EmmanuelBeziat** [comment]
Hi @OmarOdaini,

Done, check out the new 2.1.85 version :)

Thanks!

**Comment by OmarOdaini** [comment]
Thanks for the quick action!
