### ISSUE TITLE
Solidity icons are too big

### ISSUE THREAD

**Issue by lucassaldanha** [EmmanuelBeziat/vscode-great-icons#231]
Hi,

I have just started using this extension and I love the icons. However, the icon for Solidity files seems to be too big. I'm not sure if it is a matter of the icon file being too big or some configuration missing.

<img width="240" alt="Screen Shot 2022-04-05 at 10 00 45 AM" src="https://user-images.githubusercontent.com/1766440/161639735-e1946bc5-1b86-4ca0-85b1-554ea2be8ecf.png">

I'd be happy to help with a PR but I need some directions. Cheers!

**Comment by EmmanuelBeziat** [comment]
Hi @lucassaldanha 

It's too big indeed! I fixed it, check out the new 2.1.85 version :)

Thanks!

**Comment by lucassaldanha** [comment]
Thanks for the quick fix! I'll check it out!
