### ISSUE TITLE
Godot file icon support

### ISSUE THREAD

**Issue by ToyWalrus** [EmmanuelBeziat/vscode-great-icons#232]
## Format to support

* [Godot file](https://godotengine.org/)
* Files extensions: *.gd, *.tscn
* Official icon ![godot](https://user-images.githubusercontent.com/25328178/163598171-660542bd-85d5-4faa-a93e-54ac0b10c076.svg)

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay. Check out the new v2.1.88!
