### ISSUE TITLE
Tailwind CSS file icon support :)

### ISSUE THREAD

**Issue by Dav3whit3** [EmmanuelBeziat/vscode-great-icons#233]
Hi man, could be awesome if you could add support for my favourite css framework :) Cheers m8

* tailwind.css files
* Official icon (link or image) [https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_tailwind.svg](url)
* Files extensions: 
     filenamesGlob: ['tailwind', 'tailwind.config'],
      extensionsGlob: ['js', 'ts'],

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay. Check out the new v2.1.88!
