### ISSUE TITLE
Add Support for Tailwind CSS Config File

### ISSUE THREAD

**Issue by codingwithchris** [EmmanuelBeziat/vscode-great-icons#234]
## Format to support
Tailwind CSS Framework

* [Tailwind Config File](https://tailwindcss.com/)
* Official white bg icon (https://tailwindcss.com/favicons/apple-touch-icon.png?v=3)
* Official mased svg Icon (https://tailwindcss.com/favicons/safari-pinned-tab.svg?v=3)
* Files extensions: *.config.js, *.config.cjs
* Specific files names: tailwind.config.js, tailwind.config.cjs

Their icon is usually present without a white background... the make SVG doesn't have a color with it but I'm assuming you can apply their color to it?

Thank you so much!

**Comment by EmmanuelBeziat** [comment]
#233

**Comment by codingwithchris** [comment]
You rock! Thank you!! 🔥🎉

**Comment by codingwithchris** [comment]
@EmmanuelBeziat Just checking in to see if you've been been able to look into adding this icon :) Appreciate ya!

**Comment by codingwithchris** [comment]
Afg... didn't mean to close it 🤦‍♂️

**Comment by codingwithchris** [comment]
@EmmanuelBeziat Is this project still active/maintained?

**Comment by EmmanuelBeziat** [comment]
@codingwithchris yes, sorry I just never took the time to address the last requests. I'll kick myself in the butt to get it all done before tomorrow.

**Comment by EmmanuelBeziat** [comment]
There, sorry for the long delay. Check out the new v2.1.88!

**Comment by codingwithchris** [comment]
@EmmanuelBeziat Ih man!! Thank you!! That's awesome! Much appreciated!
