### ISSUE TITLE
Allow customised file/folder matching for icons

### ISSUE THREAD

**Issue by SpenceUK** [EmmanuelBeziat/vscode-great-icons#235]
Allow users in the vscode settings to add additional file/folder name mappings for icons.

For example: `docker-compose.yml` matches the docker icon but variations like `docker-compose-dev.yml` or `docker-compose.dev.yml` do not match.

**Comment by bietdoikiem** [comment]
I'm also having the same request for this, as currently there are unmatched icons when dealing with Typescript Nestjs structure as well like `**.service.ts` files.

**Comment by EmmanuelBeziat** [comment]
Hi,
Unfortunately, it seems that it requires a lot of dev to have a customizable override property, while this icon set is very lightweight (basically nothing but a json file).

I've added the suggested namefiles tho, and can add more to suit your needs, feel free to open a specific ticket :) Thanks!
