### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by omegaicon** [EmmanuelBeziat/vscode-great-icons#236]
## Format to support

* [Type of file](https://pnpm.io/)
* Official icon (https://pnpm.io/logos)
* Files extensions: *.yaml, *.cjs
* Specific files names: (if required; for example: gulpfile.js) pnpm-workspace.yaml, .pnpmfile.cjs, pnpm-lock.yaml

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay. Check out the new v2.1.88!
