### ISSUE TITLE
Assembly support

### ISSUE THREAD

**Issue by kosude** [EmmanuelBeziat/vscode-great-icons#237]
## Format to support

* Type of file: Assembly files (no official website)
* No official icon, although [seti-ui](https://github.com/jesseweed/seti-ui/blob/master/icons/asm.svg) has implemented a good one (colour `#cc3e44`)
* Files extensions: *.asm, *.s
* No specific file names

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay. Check out the new v2.1.88!
