### ISSUE TITLE
Sentry.io icon support

### ISSUE THREAD

**Issue by rafakwolf** [EmmanuelBeziat/vscode-great-icons#238]
## Format to support

* [Type of file](https://sentry.io/)
* Official icon (![sentry-3](https://user-images.githubusercontent.com/2060578/185140856-ebf7c3e5-db5b-4393-b1e4-0e22142aa20b.svg))
* Files extensions: *.sentryclirc
* Specific files names: sentry.client.config.js/ts, sentry.server.config.js/ts, sentry.properties

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay. Check out the new v2.1.88!
