### ISSUE TITLE
yml and bicep icons

### ISSUE THREAD

**Issue by tiagoacosta17** [EmmanuelBeziat/vscode-great-icons#241]
yml or yaml extension on file do not trigger the icon :) 

also would be nice a new icon for .bicep files :) 

thanks for the amazing work. 

![image](https://user-images.githubusercontent.com/111350555/192476568-4d3cb022-3f0a-4c57-9421-94c7cf955706.png)

**Comment by luc-ass** [comment]
Yep, same here. *.yml and *.yaml are not recognised.
Thanks for the amazing icons!

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay. Check out the new v2.1.88!

The yaml/yml issue seem to happen every now and then for a few people, usually removing and reinstalling the set solves the issue.
