### ISSUE TITLE
Browserslist's config icon not picked up.

### ISSUE THREAD

**Issue by vetaltor** [EmmanuelBeziat/vscode-great-icons#242]
Hi,

I found out recently that my [Browserslist](https://github.com/browserslist/browserslist) default config was wrongly named, yet it was using correct icon.

File name was *.browserlistrc*
![image](https://user-images.githubusercontent.com/16205107/195096365-a594ef8c-fcce-4042-a881-4703ad562655.png)

...while a correct default config has to be named *.browser**s**listrc*
![image](https://user-images.githubusercontent.com/16205107/195097210-3e310d6f-5ae7-47b5-843e-2a4179202f90.png)

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay. Check out the new v2.1.88!
