### ISSUE TITLE
Can you add this plug-in on webstorm?

### ISSUE THREAD

**Issue by Sakura0122** [EmmanuelBeziat/vscode-great-icons#243]

**Comment by KevinYangzzz** [comment]
Agree. This theme looks great and is helpful to develop. It would be better much if we can use in Webstorm

**Comment by EmmanuelBeziat** [comment]
Hi!
Unfortunately, I don't use Webstorm myself, and have no knowledge on creating an icon set on it. If you have any will of doing it by yourself, feel free to make a fork version for it:)
