### ISSUE TITLE
[BUG] No Prettier icon for .prettierrc.cjs

### ISSUE THREAD

**Issue by amokmen** [EmmanuelBeziat/vscode-great-icons#244]
Subj.

Ubuntu 18, VSCode 1.73, VSCode Great Icons 2.1.86

Screenshot:
![image](https://user-images.githubusercontent.com/10855248/200115363-2106a94b-2bff-4c03-8552-bbb42fd4b6be.png)

**Comment by Clm-Roig** [comment]
Same here on Windows 10, v2.1.86. 

More precisely, all prettier file names don't work except one : `.prettierrc`

There was a recent PR about Prettier here --> #239

**Comment by Clm-Roig** [comment]
Maybe there is a conflict between `prettierrc` in the `fileExtensions` section : 
https://github.com/EmmanuelBeziat/vscode-great-icons/blob/889d892c627b4a703dab103fd7ef5886b7c436f8/icons.json#L1089

And all the `prettierrc` in the `fileNames` section below ? 
https://github.com/EmmanuelBeziat/vscode-great-icons/blob/889d892c627b4a703dab103fd7ef5886b7c436f8/icons.json#L1392-L1401

Prettier is the only tool which has this pattern (extension + fileName) maybe ? Not sure at 100%, I didn't search and find every extension 😅

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay. Check out the new v2.1.88!
