### ISSUE TITLE
Add Vercel Logo for Vercel Config

### ISSUE THREAD

**Issue by codingwithchris** [EmmanuelBeziat/vscode-great-icons#246]
## Format to support

* [Config File](https://vercel.com/docs/project-configuration) for [Vercel](https://vercel.com)

* Official icon (link or image)
![vercel-logo](https://user-images.githubusercontent.com/17693193/208107672-a1d75d1e-34fb-4454-83da-f0151eb6cb58.svg)
![vercel-logo-2](https://user-images.githubusercontent.com/17693193/208107673-24e7b0f1-79c6-4a5b-9c55-4f8f1fc612bc.png)

* Files extensions: *.json

* Specific files names: vercel.json

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay. Check out the new v2.1.88!
