### ISSUE TITLE
NextJS Config File Support

### ISSUE THREAD

**Issue by codingwithchris** [EmmanuelBeziat/vscode-great-icons#247]
## Format to support

* [NextJS](https://nextjs.org/) Config File

* OFFICIAL icon (link or image)
![next-icon](https://user-images.githubusercontent.com/17693193/208108333-4494f514-c618-41a1-a671-bcf80e258537.png)
![next-icon-white](https://user-images.githubusercontent.com/17693193/208108334-c4298180-a630-4088-a6ef-46ceac088eb0.png)

* Files extensions: *.js, *.mjs

* Specific files names:
next.config.js, next.config.mjs

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the long delay. Check out the new v2.1.88!
