### ISSUE TITLE
NextJS Icon Improvments

### ISSUE THREAD

**Issue by codingwithchris** [EmmanuelBeziat/vscode-great-icons#248]
The NextJS Icon was merged in #247! This was awesome! Thank you!

However, the coloring is a little off from their brand. I'm wondering if it should just be black with a little white behind the cutout N? Whatever you think might work.

**Comment by EmmanuelBeziat** [comment]
It's often hard to get black and/or white icons to work great on both dark and light themes. I'll figure something, a white background circle might do the trick.

**Comment by EmmanuelBeziat** [comment]
@codingwithchris There you go, sorry for the extensively long delay.

Check out the new version and tell me what do you think. :)
