### ISSUE TITLE
divers logos to png and ico

### ISSUE THREAD

**Issue by vladrbyte** [EmmanuelBeziat/vscode-great-icons#249]
## Format to support

* [ICO](https://docs.fileformat.com/image/ico/)

* Files extensions: *.ico, 

![Screenshot_20230217_094042](https://user-images.githubusercontent.com/61164697/219595658-c5f3bae7-2422-44ec-ab90-502c37a26f0f.png)

**Comment by EmmanuelBeziat** [comment]
Hi!
I've added a specific icon for `.ico` files, but it's not easy to be very specific for an icon. :) 
Check out the new v2.1.9.1
