### ISSUE TITLE
Add support for header files in C and C++

### ISSUE THREAD

**Issue by EmmanuelBeziat** [EmmanuelBeziat/vscode-great-icons#25]
## header files for c and c++

* Files extensions: *.h, *.hpp
https://github.com/EmmanuelBeziat/vscode-great-icons/issues/17#issuecomment-268512647

@BillDenton

**Comment by EmmanuelBeziat** [comment]
Hi @BillDenton,

Header files for C++ were already inside, so I added support for C (.*h). Is it okay now? :)

Thanks!

**Comment by BillDenton** [comment]
That sounds good. Has an update been sent to the market place?

**Comment by EmmanuelBeziat** [comment]
Yes, just made it. You shouls see it by now. :)

**Comment by BillDenton** [comment]
They are showing up as a blue C, which is the same as C files. That makes it tricky to distinguish.

**Comment by EmmanuelBeziat** [comment]
Hum well, those icons are meant to distinguish files by language, and… .h are C and .hpp are C++, right?

But we can discuss about this. Do you have an example of icon used in other IDE (or other icon set)? I could use it to have an idea on how to separate them properly. Or maybe just playing on the icon color?

What are you used to?

**Comment by BillDenton** [comment]
At the moment, I'm using [VSCode Icons](https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons), which distinguishes ".c" and ".h" (a blue C and H), but doesn't shown different icons for ".cpp" and ".hpp" (both a blue C++ with the ++ smaller starting inside the C). I would like .cpp, .hpp, .c and .h to allow have different icons. I suggest C++, H++, C and H respectively.

**Comment by EmmanuelBeziat** [comment]
I'm not a big fan of it, it really looks like it’s a whole new language… But there you go. :)

**Comment by BillDenton** [comment]
Thanks. Just updated and checked and looks good.
