### ISSUE TITLE
Astro File Support

### ISSUE THREAD

**Issue by teddzyb** [EmmanuelBeziat/vscode-great-icons#251]
## Format to support

* [Astro](https://astro.build)
* [Official icon](https://astro.build/press/)
* Files extensions: *.astro

**Comment by teddzyb** [comment]
Woops, my bad. The Astro format is already supported. The icon didn't load the first time I checked for some reason.

**Comment by EmmanuelBeziat** [comment]
@teddzyb no problem ;)
