### ISSUE TITLE
Makefile icon doesn't correspond to icon sheet

### ISSUE THREAD

**Issue by eirys** [EmmanuelBeziat/vscode-great-icons#257]
Title says all, here is what I got instead (which isn't great in my humble opinion, due to the weird outline). I don't think it fits the overall aesthetic too.
![image](https://user-images.githubusercontent.com/80129590/236645052-3a708429-4fdc-4a6d-9ac1-80a7f3f64a71.png)
Awesome pack though :)

**Comment by EmmanuelBeziat** [comment]
Hi, 

Sorry for the long delay. Check out the new v2.1.93!
