### ISSUE TITLE
[Suggestion] properties/ini files

### ISSUE THREAD

**Issue by cootshk** [EmmanuelBeziat/vscode-great-icons#258]
## Config files

* [Properties file](https://fileinfo.com/extension/properties#java_properties_file)
* VSCode default icon ![image](https://user-images.githubusercontent.com/83678457/236652805-5e49ccc3-4030-4452-91e2-817f7a0016e0.png)
* Files extensions: *.properties, *.ini

example file:
```properties
[Hello]
hi=true
ello=4
list=["hi","hello","hola"]

[Goodbye]
bye=sometimes
cya=3
list=["bye","goodbye","adios"]
```

**Comment by cootshk** [comment]
You can use the same icon as .conf files

**Comment by EmmanuelBeziat** [comment]
Hi, 

Sorry for the long delay. Check out the new v2.1.93!
