### ISSUE TITLE
Request more folder/directory icons

### ISSUE THREAD

**Issue by ngdangtu-vn** [EmmanuelBeziat/vscode-great-icons#259]
## Format to support

There are lot popular dirs that have been used such as: img/image,  dist, bak/backup, svg, theme/themes, plugin/plugins, asset/assets/res/resource/resources, inc/include, font/fonts, view/html, style/css, script/js, etc.

I think it would be helpful to add more dir icon for those case as well.

**Comment by EmmanuelBeziat** [comment]
Hi,

Sure, I'll add a few soon. :)

**Comment by EmmanuelBeziat** [comment]
Hi @ngdangtu-vn

I've added a few folders, check the new version. I'll keep adding more in future updates.

Thanks!
