### ISSUE TITLE
Makefile (*.mk) type

### ISSUE THREAD

**Issue by fadeevab** [EmmanuelBeziat/vscode-great-icons#26]
## Format to support: Makefile - *.mk

* Makefile: *.mk (https://www.file-extensions.org/mk-file-extension)
* Official icon (the same as for "makefile")
* Files extensions: *.mk
* Specific files names: "makefile" is already added, request is to add "mk" file extension.

**Comment by EmmanuelBeziat** [comment]
Hi,

I’ll do this quickly

**Comment by fadeevab** [comment]
Thank you!

**Comment by EmmanuelBeziat** [comment]
Here you go :)

**Comment by fadeevab** [comment]
:+1:  Don't forget to make update of the package :)

**Comment by EmmanuelBeziat** [comment]
It was done the moment I made the update (1.1.31) ; you don‘t have the notification?

**Comment by fadeevab** [comment]
Hm, strange, auto-update is disabled, but I see the 1.1.31 version in package manager. Maybe I don't see update because I fixed your package manually (locally) to add support .mk and he doesn't see a diff (?) (but most probably package manager considers only version number) Just never mind, no problems. Maybe I just forgot that I updated the package manually :)

**Comment by EmmanuelBeziat** [comment]
Ultimately, you can remove and reinstall it, that should solve the problem.

**Comment by fadeevab** [comment]
Requested https://github.com/Microsoft/vscode/issues/17847
The issue was in settings user experience, it is not clear: I had autoUpdate enabled, but it's hard to get it.

**Comment by EmmanuelBeziat** [comment]
Thanks for the tip!
