### ISSUE TITLE
NextJS App Folder Custom Icon

### ISSUE THREAD

**Issue by DarpNagarsheth** [EmmanuelBeziat/vscode-great-icons#269]
## Format to support

* [Type of file] Next JS App Folder
* Official icon: https://www.youtube.com/watch?v=gSSsZReIFRk can see in this video at 0:12 
* Files extensions: It's a folder like src
* Specific files names: app

For NextJS can you please show the App folder as a different icon similar to src or something like in the video linked? I love the theme and design of your icons that icon is from vscode-icons but I'm not a fan of that package. 

If you can add something like that in this bundle that would be great! Thank you!
@EmmanuelBeziat

**Comment by EmmanuelBeziat** [comment]
Hi @DarpNagarsheth 

I've added app and .next folder, check the new version to see if that suits your needs :)

**Comment by surjithctly** [comment]
Damn, I came here to request the opposite. app icon should look same as other folders. To me, it looks like a settings folder, but the entire project is inside. Any chance we could get a configurable option to set it as normal folder icon?

![CleanShot 2024-01-14 at 13 18 41](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/1884712/c856ca09-f7c2-4752-96ec-81ea2efa207d)

**Comment by EmmanuelBeziat** [comment]
@surjithctly Unfortunately, settings are not possible as of now. It would require me to completely code the whole thing to become something else than just an icon set and be a full plugin… This is something I keep in mind, but I can't tell you that it could be done soon.
