### ISSUE TITLE
Associate the ruby icon with additional extensions.

### ISSUE THREAD

**Issue by seraku24** [EmmanuelBeziat/vscode-great-icons#27]
You already have a nice Ruby icon which covers `.rb` and `.gemfile`.  Would it make sense to extend that to cover other common Ruby-related files:
- Gem specification: `.gemspec`
- Encapsulated Ruby: `.erb`
- Rake files: `.rake`, `.rakefile`

Of course, since Rake is basically make, perhaps its files should use the same "settings" icon that you have associated with `makefile`.

Just a thought.  `(:`

**Comment by EmmanuelBeziat** [comment]
Hi,
It's done. Keeping the same icon that makefiles for rake and rakefiles was a good idea.

You’ll find this in the v1.1.32 release, just published a second ago. :)

**Comment by seraku24** [comment]
Thanks, @EmmanuelBeziat!

Although, I must apologize that I forgot to mention the extension-less file `Rakefile` occurs as well, similar to `makefile`.  I will, of course, now go sit in a corner and think about what I've done.

**Comment by EmmanuelBeziat** [comment]
No problem, will be done in a minute. Get ready for v1.1.33 ;)
