### ISSUE TITLE
"Open folder" icon is showing as "closed folder"

### ISSUE THREAD

**Issue by rodrigocfd** [EmmanuelBeziat/vscode-great-icons#271]
I just updated to latest v2.1.95, and open folders are displaying the "closed folder" icon. It seems to be a bug.

Screenshot:

![open-folders](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/1283868/00ed6c6b-f424-4d79-b352-7fb620c6fe12)

**Comment by EmmanuelBeziat** [comment]
Hello @rodrigocfd 

That's totally my fault. Update to v2.1.96, it's fixed. Thanks !
