### ISSUE TITLE
Add Brainf**k icon (Esolang)

### ISSUE THREAD

**Issue by RatoGBM** [EmmanuelBeziat/vscode-great-icons#272]
## Brainfuck

[Ecolang website](https://esolangs.org/wiki/Brainfuck)

Brainf*ck uses the `.bf` (and `.b`) file names.

Because brainfuck doesn't have an official icon (or even website) as far as I am aware, I designed my own icon... You are free to not add it or find a different one.

![brainfuck](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/80184495/05832f36-0b9f-43c9-907f-63103d83818d)

I used [Graphite Editor](https://dev.graphite.rs/) to design it. So here is the source file in case you want to edit it: 
[brainfuck.graphite.zip](https://github.com/EmmanuelBeziat/vscode-great-icons/files/12298672/brainfuck.graphite.zip)

**Comment by EmmanuelBeziat** [comment]
Hi!

The icon was too complex in its state for the small size of vscode icons, so I made a more simplistic one, but I kept the idea of the two brain sides :)

It has been added in the new v2.1.98, check it out!

Thanks!

**Comment by RatoGBM** [comment]
thanks, if it looks better I have no complains.
