### ISSUE TITLE
golang icon should be different

### ISSUE THREAD

**Issue by radoslew** [EmmanuelBeziat/vscode-great-icons#274]
I have the impression that this icon is not very intuitive and poorly distinguished (on many monitors it simply looks like a blue spot). Classic GO icon from "VSCode Icons" is much more ergonomic in my opinion! What do you think?

**Comment by EmmanuelBeziat** [comment]
Hi! I'll check that and eventually revamp the icon :)

**Comment by radoslew** [comment]
Once again EB - maybe let's just use the classic icon? I think it is much more recognizable, distinguishable and ergonomic on smaller screens/resolutions. "Gopher" is nice, but it's really not the best icon in this case. I think my arguments are also reasonable and it's not just "this icon is ugly - you should change it to the one I like!" - we have to make compromises for the greater good!
Cheers mate!
![golang-1](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/80459029/95f78e7a-9ae1-4679-9393-4d7cbf581514)

**Comment by EmmanuelBeziat** [comment]
@radoslew Hi,

It has now been updated, check out the new 2.1.99 version ! :)

**Comment by radoslew** [comment]
> > @radoslew Hi,
> > 
> > It has now been updated, check out the new 2.1.99 version ! :)
> 
> I saw this new icon in today's update, and it does improve visibility compared to the old icon. However, I don't agree with the additional white border. It looks like an unclean cutout and doesn't harmonize well with themes that have non-white background colors, such as this Tab image. I hope the white border can be removed. Thank you.
> ![Uploading 截屏2023-09-18 18.34.08.png…]()
> 

100% agree. White border make it look bad.

**Comment by EmmanuelBeziat** [comment]
> I saw this new icon in today's update, and it does improve visibility compared to the old icon. However, I don't agree with the additional white border. It looks like an unclean cutout and doesn't harmonize well with themes that have non-white background colors, such as this Tab image. I hope the white border can be removed. Thank you. 

Seeing it live, it indeed looked unclean. I removed the border, let me know how it is now.

**Comment by jzksnsjswkw** [comment]
> > I saw this new icon in today's update, and it does improve visibility compared to the old icon. However, I don't agree with the additional white border. It looks like an unclean cutout and doesn't harmonize well with themes that have non-white background colors, such as this Tab image. I hope the white border can be removed. Thank you.
> 
> Seeing it live, it indeed looked unclean. I removed the border, let me know how it is now (v2.1.100).

It looks much better now! If I had to point out any flaws, it would be perfect if it could be slightly enlarged and the color could be darkened just a bit. This is because in the Go project, there is a "gomod" file, and it doesn't have a specific icon, making it look inconsistent with the Go files. This is a minor flaw that can be changed or left as it is; it's already looking great.

**Comment by radoslew** [comment]
Now it's fine, but I agree with @jzksnsjswkw in terms of size and color. Also please remember about #270 - you promised to add more icons there ;)

**Comment by EmmanuelBeziat** [comment]
@jzksnsjswkw I just pushed a new version, that should do it. Also added support for the `go.mod` file. :)

**Comment by jzksnsjswkw** [comment]
It looks much better now :). 
However, "gomod" and "gosum" are dependency management files for Go projects, not code files. Using the same icon can be confusing. You can differentiate them by changing their colors, similar to the "Material Icon Theme" theme.
