### ISSUE TITLE
Add cython icon

### ISSUE THREAD

**Issue by yunline** [EmmanuelBeziat/vscode-great-icons#275]
## Cython

* [Cython website](https://cython.org/)
* Official icon  
    ![image](https://avatars.githubusercontent.com/u/486082?s=48&v=4)
    ![image](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/31395137/9cf9deee-03ba-487c-b7b6-89dd4f0cd40b)
* Files extensions: `.pyx` `.pxd`

**Comment by EmmanuelBeziat** [comment]
Hi!

The icon has been added in the new v2.1.98, check it out :)

Thanks!
