### ISSUE TITLE
Add icon for .zig

### ISSUE THREAD

**Issue by CodyKoInABox** [EmmanuelBeziat/vscode-great-icons#277]
## Format to support

* [.zig](https://ziglang.org/)
* Official icon: https://avatars.githubusercontent.com/u/27973237?s=160&v=4
![image](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/125526050/85001177-894b-4516-93e7-e29e31c26f4c)
* Files extensions: *.zig

**Comment by CodyKoInABox** [comment]
https://ziglang.org/

**Comment by CodyKoInABox** [comment]
Zig is a general-purpose programming language and toolchain for maintaining robust, optimal and reusable software.
https://ziglang.org/

**Comment by EmmanuelBeziat** [comment]
Hi!

The icon has been added in the new v2.1.98, check it out :)

Thanks!

**Comment by CodyKoInABox** [comment]
Amazing! Thank you =)
