### ISSUE TITLE
An icon for `vr.js`

### ISSUE THREAD

**Issue by Brianzchen** [EmmanuelBeziat/vscode-great-icons#279]
## Format to support
Would it be possible have a vr test icon for the extension `vr.*` which may be like `index.vr.js` or `index.vr.ts`

**Comment by EmmanuelBeziat** [comment]
Hi!
Sorry for the long delay. Icon is added in the new 2.1.103 version! Couldn't find much about this format tho, so not sure this is the right icon to use. Let me know what you think.
