### ISSUE TITLE
Add an icon for Gherkin (.feature) files.

### ISSUE THREAD

**Issue by seraku24** [EmmanuelBeziat/vscode-great-icons#28]
## Gherkin (.feature) files

* [Gherkin language wiki](https://github.com/cucumber/cucumber/wiki/Gherkin)
* Logo from `cucumber` project: ![](https://raw.githubusercontent.com/cucumber/cucumber/master/docs/images/cucumber.png)
* Icon from `vscode-cucumber` project: ![](https://raw.githubusercontent.com/stevejpurves/vscode-cucumber/master/images/cukes.png)
* Files extensions: `*.feature`
* Specific files names: *(none that I am aware of)*

**Comment by EmmanuelBeziat** [comment]
Hi,
There you go: gherkin files added into 1.1.33, just released a second ago. :)
