### ISSUE TITLE
Icon request: PRQL

### ISSUE THREAD

**Issue by vanillajonathan** [EmmanuelBeziat/vscode-great-icons#281]
## Format to support
PRQL is a modern language for transforming data — a simple, powerful, pipelined SQL replacement.

* [PRQL](https://prql-lang.org/)
* Official icon: https://github.com/PRQL/prql-brand
* Files extensions: `*.prql`

**Comment by EmmanuelBeziat** [comment]
Hi!
Sorry for the long delay. Icon is added in the new 2.1.103 version!
