### ISSUE TITLE
Spring graphql schema files

### ISSUE THREAD

**Issue by jam3smay** [EmmanuelBeziat/vscode-great-icons#282]
Can you support extensions used by Spring for graphql schemas for the existing graphql file icon: https://github.com/EmmanuelBeziat/vscode-great-icons/blob/main/icons/graphql.svg

By default, the Spring Boot starter looks for schema files with extensions ".graphqls" or ".gqls" under the location... https://docs.spring.io/spring-graphql/docs/1.1.0-M1/reference/html/#execution-graphqlsource-schema-resources

File Icon: https://github.com/EmmanuelBeziat/vscode-great-icons/blob/main/icons/graphql.svg
File Extensions: *.graphqls and *.gqls (in addition to the existing mappings *.graphql and *.gql)

**Comment by jam3smay** [comment]
Or possibly a slightly different icon for graphqls | gqls **_schema files_** vs. graphql or gql files. Either way it would be great to have file icon support for these. Thnx!

**Comment by EmmanuelBeziat** [comment]
Hi!
Sorry for the long delay. Icon is added in the new 2.1.103 version!
