### ISSUE TITLE
Icon request: swi-prolog

### ISSUE THREAD

**Issue by EySword** [EmmanuelBeziat/vscode-great-icons#284]
* swi-prolog

* Full logo: https://www.swi-prolog.org/icons/vector/swipl-logo.svg
Full logo without text: https://starbeamrainbowlabs.com/images/logos/swi-prolog.svg

* Files extensions: *.pl

**Comment by EmmanuelBeziat** [comment]
Hi!
Sorry for the long delay. Unfortunately, the *.pl extension is already used by pearl language… The prolog doc says they support the *.pro extension, I added this one, I hope that'll help.
