### ISSUE TITLE
No Icon Present for groovy script file

### ISSUE THREAD

**Issue by Adnan-110** [EmmanuelBeziat/vscode-great-icons#286]
## Format to support

groovy script
https://groovy-lang.org/
.groovy

**Comment by Adnan-110** [comment]
official Icon Link : https://images.app.goo.gl/XLnWVayPxpx4NMsf7

**Comment by EmmanuelBeziat** [comment]
Hi!
Sorry for the long delay. Icon is added in the new 2.1.103 version!
