### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by purechromas** [EmmanuelBeziat/vscode-great-icons#287]
![image](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/117194824/6b425a54-6b47-428c-8a0a-d7a6a7de6165)

There is no icon for just docker file if u can fix that would be great, thanks!

**Comment by EmmanuelBeziat** [comment]
Hi!
Sorry for the long delay. Icon is added in the new 2.1.103 version!
