### ISSUE TITLE
poetry.lock icon

### ISSUE THREAD

**Issue by purechromas** [EmmanuelBeziat/vscode-great-icons#288]
![image](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/117194824/1a27038e-8d44-48d5-b3d0-7be13578fd15)

Would be great to add same icon for .lock as .toml so we can be more clear that this is poetry (for python).

**Comment by johanguse** [comment]
Same to bun lock

**Comment by EmmanuelBeziat** [comment]
Hi!
Sorry for the long delay. Icon is added in the new 2.1.103 version!

@johanguse which
