### ISSUE TITLE
change c file icon

### ISSUE THREAD

**Issue by sunbines** [EmmanuelBeziat/vscode-great-icons#289]
The c file icon is owercase, and c-h file icon is uppercase, which is not a good match. It's very ugly.

![image](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/35656677/eba583b4-d125-475e-ae75-e78ad5a43db2)
You can use the file I designed:
![c](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/35656677/ccc5bc50-a1f6-467a-acd7-685192ab2d8e)

https://drive.google.com/file/d/1dJ1hhtmKiHony-Fk_lbXHj70GClzl4yc/view?usp=drive_link

now：
![image](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/35656677/06be78cb-760d-4d95-a6fc-e763025a0d55)

**Comment by EmmanuelBeziat** [comment]
Hi!
Sorry for the long delay. Icon is added in the new 2.1.103 version!
