### ISSUE TITLE
Jenkinsfile icon not working properly

### ISSUE THREAD

**Issue by Adnan-110** [EmmanuelBeziat/vscode-great-icons#290]
## Jenkinsfile

* Jenkinsfile
* [Official icon (link or image)](https://shorturl.at/vBMNS)
* Files extensions: *.Jenkinsfile, *.Jenkinsfile
* If file name is just Jenkinsfile then it works fine(icon appears) but whenever file name is something like abc.Jenkinsfile or xyz.Jenkinsfile it does not work(icon does not appear) 
![image](https://github.com/EmmanuelBeziat/vscode-great-icons/assets/69635633/e04498a9-b34a-4825-a328-70d5e02d94cd)

**Comment by EmmanuelBeziat** [comment]
Hi!
Sorry for the long delay. It's now extended to work with *.jenkinsfile :)
