### ISSUE TITLE
Opencl file icon

### ISSUE THREAD

**Issue by Lukz127** [EmmanuelBeziat/vscode-great-icons#294]
Just a simple feature request. Opencl icon. I didn't find anything that would fit the stile of this icon collection but maybe you will have better luck. Opencl uses the .cl file extension.
Thanks in advance.

**Comment by Bonniemarie216** [comment]
``

**Comment by EmmanuelBeziat** [comment]
Hi @Lukz127

Since it's a language used for Cuda, i went for the nvidia logo. Tell me if it's good for you!
Check out the new version.

Thanks!

**Comment by Lukz127** [comment]
Yes it's great thank you very much.
