### ISSUE TITLE
coldfusion files

### ISSUE THREAD

**Issue by arowolo** [EmmanuelBeziat/vscode-great-icons#3]
Hi,

Can you kindly add coldfusion file types (.lucee, .cfc, .cfm and .cfml)
Nice job

Thanks

**Comment by EmmanuelBeziat** [comment]
hi,
Okay, I'll add them before the end of the day. Thanks for your feedback!

**Comment by EmmanuelBeziat** [comment]
Here you go! Let me know if something’s wrong.

Thanks!
