### ISSUE TITLE
.slim does not work

### ISSUE THREAD

**Issue by debbbbie** [EmmanuelBeziat/vscode-great-icons#30]

**Comment by debbbbie** [comment]
![image](https://cloud.githubusercontent.com/assets/233115/21598010/287f23dc-d18f-11e6-8479-73be2b253b0f.png)

**Comment by EmmanuelBeziat** [comment]
Hi! 
Thanks for pointing this. It’s solved now, get the 1.1.36 version in a few minutes. :)

**Comment by zackirby** [comment]
Could this get updated to also include the .slm extension? It's a port of .slim but slimmer :). More info here: https://github.com/slm-lang/slm

**Comment by EmmanuelBeziat** [comment]
Hi @zackirby 

Sorry for the long delay, it's now fixed in the new 2.1.48 version
