### ISSUE TITLE
Icon request: Vitest `*.test-d.ts` type test files

### ISSUE THREAD

**Issue by danwithabox** [EmmanuelBeziat/vscode-great-icons#303]
## Format to support

* Vitest [*.test-d.ts](https://vitest.dev/guide/testing-types)
* Official icon: I guess same as `*.spec.*` and `*.test.*`, [test.svg](https://github.com/EmmanuelBeziat/vscode-great-icons/blob/main/icons/test.svg)
* Files extensions: `*.test-d.ts`

To my surprise this doesn't seem to have been requested yet, not many people using Vitest type tests I guess 😄 

Cheers!

**Comment by EmmanuelBeziat** [comment]
Hello @danwithabox,
Thanks for pointing this out! It's now added in the new v2.1.107 :)

**Comment by danwithabox** [comment]
Thanks for the quick turnaround, my test folder no longer looks wonky 😄
Love the extension, and according to the changelog, happy birthday as of yesterday!
Cheers!

**Comment by EmmanuelBeziat** [comment]
Thanks a lot! :) I'm happy to know that people like my (not so) little icon set.
