### ISSUE TITLE
Request for .cursorrule File Icon Support

### ISSUE THREAD

**Issue by Itakello** [EmmanuelBeziat/vscode-great-icons#304]
## Request for New Icon

I'd like to request an icon for the `.cursorrule` file extension, which is currently not supported by the VSCode Great Icons extension. This file type is crucial for my development environment, and having a dedicated icon would improve the visibility and recognition of these files in the editor.

### Details:
- **Type of file:** Configuration File
- **Files extensions:** `.cursorrule`
- **Suggested Icon:** https://res.cloudinary.com/apideck/image/upload/w_196,f_auto/v1679697469/icons/cursor-so.png

Thank you for considering this addition!

**Comment by EmmanuelBeziat** [comment]
Hello @Itakello 

I've added the official cursor icon for the moment. I'll make a more fitting one to match the rest of the icon set later. Check out the new v2.1.108, let me know what you think about it.

Thanks!

**Comment by Itakello** [comment]
I'm sorry, but the issue was incorrect. Cursor uses ".cursorrules", not ".cursorrule" files...
Could you add the final "s" to the file name? Thanks.

**Comment by EmmanuelBeziat** [comment]
Hi @Itakello 

It's fixed! Check out the new v2.1.109!
