### ISSUE TITLE
Icon for CUE

### ISSUE THREAD

**Issue by nxcc** [EmmanuelBeziat/vscode-great-icons#306]
## cue

* [CUE aka cuelang](https://cuelang.org/)
* Official icon (https://cuelang.org/)
* Files extensions: *.cue
* Specific files names: cue.mod (folder)

**Comment by EmmanuelBeziat** [comment]
Hi @nxcc 

The icon have been added. I've tried to get it simple and visible on both dark and light themes. Let me know what you think.
Check out the new v2.1.109!

Thanks :)

**Comment by nxcc** [comment]
Hi @EmmanuelBeziat,
thanks for incorporating this icon so fast! Unfortunately it's hard to recognize, at least on my Monitor. I guess the logo is just not made to be displayed at such a small size ;-) (cf. https://ibb.co/s5FG5L6)

**Comment by EmmanuelBeziat** [comment]
Okay, I'll try to make a better version of it!

**Comment by EmmanuelBeziat** [comment]
@nxcc It should be better now, let me know what you think. Check out the new v2.1.110!

**Comment by nxcc** [comment]
@EmmanuelBeziat definetly better, thanks.
