### ISSUE TITLE
Liquid

### ISSUE THREAD

**Issue by EmmanuelBeziat** [EmmanuelBeziat/vscode-great-icons#31]
## Liquid

* [Type of file](https://shopify.github.io/liquid/)
* Official icon (link or image)
* Files extensions: *.liquid
* Specific files names: ?

https://github.com/EmmanuelBeziat/vscode-great-icons/issues/17#issuecomment-271204022

**Comment by EmmanuelBeziat** [comment]
Hi @czifro

Thanks for asking. I will do it during the day. Stay tuned!

**Comment by czifro** [comment]
Great! Thank you!

**Comment by EmmanuelBeziat** [comment]
It's done. You can find it in the new 1.1.37 version.

Thanks!
