### ISSUE TITLE
Please add Icons Associated with PowerShell

### ISSUE THREAD

**Issue by Riddickulus** [EmmanuelBeziat/vscode-great-icons#32]
I've just  learned that VSCode supports editing PowerShell scripts quite well, so the icons associated with PowerShell would make a great addition to this icon set....  The following are the most common PoSh filetypes:

PowerShell Repo: [https://github.com/PowerShell/PowerShell](url)

.ps1 (Powershell Script)
.psc1 (PowerShell Console File)
.psm1 (PowerShell Module File)
.ps1xml (PowerShell Type or Format Definition XML File)
.psd1 (PowerShell Data File)
.pssc (PowerShell Session Configuration File)

As you can see from the included picture, only the first two have a unique PowerShell icon.   The last 4 all have one of two types of notepad icons because,  by default, they open up in the notepad application.   I was hoping to see at least the .ps1 and .psm1 added, as those are the ones that most people would be editing in VSCode.   .ps1xml and .psd1 are also fairly common in more advanced projects.   All these file types are plain text or XML formatted text and as such, could be opened and edited in VSCode.

![image](https://cloud.githubusercontent.com/assets/4401044/21899199/4981179a-d8a4-11e6-9219-83b46a03b43f.png)

Thank you for the time you have spent and will spend working on this sweet icon set! ![bitmoji](https://render.bitstrips.com/v2/cpanel/10215973-178015617_1-s1-v1.png?transparent=1&palette=1&width=246)

Thanks,
Riddickulus

**Comment by EmmanuelBeziat** [comment]
Hi,
It’s done. You’ll find it in the new 1.1.38 version. :) 

Thanks!
