### ISSUE TITLE
*.rake Rakefile should use ruby icon

### ISSUE THREAD

**Issue by debbbbie** [EmmanuelBeziat/vscode-great-icons#33]
`*.rake`, `Rakefile`

**Comment by EmmanuelBeziat** [comment]
Hi,

Since rake is basically make, I gave it the same icon. If it's the same as ruby, won't it be a little hard to get in a ruby workflow?

What do you think?

**Comment by debbbbie** [comment]
![image](https://cloud.githubusercontent.com/assets/233115/22083544/89763156-de07-11e6-889f-c94c45d5f513.png)


![image](https://cloud.githubusercontent.com/assets/233115/22083558/999885d4-de07-11e6-8fc5-937767765382.png)

**Comment by debbbbie** [comment]
Rubymine is showing them as ruby files.

While rake is ruby make, just ruby use. And rake file use ruby grammar.

**Comment by EmmanuelBeziat** [comment]
There you go! You’ll find the new icon in v1.1.39, just released. :)

Thanks!

**Comment by debbbbie** [comment]
thanks!
