### ISSUE TITLE
Julia language support

### ISSUE THREAD

**Issue by crstnbr** [EmmanuelBeziat/vscode-great-icons#35]
## Julia language files

* Julia script file (http://julialang.org/)
* Official icon [link](https://camo.githubusercontent.com/e2323d13e8c7f5a7752d27860ccd479b7b1ce2cd/68747470733a2f2f656e637279707465642d74626e302e677374617469632e636f6d2f696d616765733f713d74626e3a414e64394763514b5f7a7251556e56484179647050695951344d6e327a775f51356d44775a53544151726976667856583672497a656478524b41) (extracted from official Julia logo)
* Files extensions: *.jl

**Comment by EmmanuelBeziat** [comment]
Hi,

You can now find this icon in the new 1.1.41 version. Thanks for asking!
