### ISSUE TITLE
Please add "test" icon for *.spec.tsx

### ISSUE THREAD

**Issue by karlfus** [EmmanuelBeziat/vscode-great-icons#36]
## *.spec.tsx

* https://basarat.gitbooks.io/typescript/content/docs/jsx/tsx.html
* No official icon, should be same as other *.spec.* files

Thanks so much for the great work!

**Comment by EmmanuelBeziat** [comment]
Hi,

There you go :) You'll find it in the new 1.1.42 version. Thanks!
