### ISSUE TITLE
BibTex icon request and pdf icon missing

### ISSUE THREAD

**Issue by czifro** [EmmanuelBeziat/vscode-great-icons#37]
## BibTex Support

* [Type of file](https://www.latex-project.org/)
* Reuse `tex` icon for bibtex
* Files extensions: *.bib
* Specific files names: *

## PDF Icon Missing

I figured I'd also report that the pdf icon is not appearing for pdf files:

![screenshot 2017-02-02 17 39 43](https://cloud.githubusercontent.com/assets/5378541/22576121/a9f0a03e-e96e-11e6-8a8f-f44f5de2bb46.png)

**Comment by EmmanuelBeziat** [comment]
Hi,
It’s done. Check out the new 1.1.43 version :)
Thanks!
