### ISSUE TITLE
Clojure icon extension

### ISSUE THREAD

**Issue by aking** [EmmanuelBeziat/vscode-great-icons#38]
Clojure/ClojureScript files need supporting :) 

* [Clojure source file](http://clojure.org)
* https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Clojure_logo.svg/2000px-Clojure_logo.svg.png
* Files extensions: *.clj *.cljs *.cljc *.edn

Thanks!

**Comment by EmmanuelBeziat** [comment]
Hi,
It’s done. Check the new 1.1.44 version! Thanks. :)
