### ISSUE TITLE
[Add Icons] CSV, Visual Studio projects and solution, C#, Paket

### ISSUE THREAD

**Issue by ArtemyB** [EmmanuelBeziat/vscode-great-icons#4]
Hi,
Here is a detailed list:
- CSV (*.csv)
- VS projects files (*.csproj, *.fsproj), solution files (*.sln, *.suo)
- C# (*.cs)
- [Paket](https://fsprojects.github.io/Paket/) (paket.references, paket.dependencies, paket.lock, paket.local) 

Would be very nice to see these additions. Thanks for your work! :)

**Comment by EmmanuelBeziat** [comment]
Hi!

Here you go, the `1.1.9` version is out with the icons you requested. Check it out, and tell me if anything is wrong.

Thanks!

**Comment by ArtemyB** [comment]
@EmmanuelBeziat thanks, I think all is nice! I thought about different icons for C# and F# projects (csproj, fsproj), but haven't found something suitable. But nevermind, it's not important at all. Thank you again! 😃

**Comment by EmmanuelBeziat** [comment]
If you get the idea, let me know. How VS is handling this?

**Comment by ArtemyB** [comment]
@EmmanuelBeziat haven't found any icons untill now. Just found out that MS provides for download a set of icons from VS. It is an archive of 2 GB (😮) size  . VS uses the following icons for projects:
- C# (*.csproj): 
![image](https://cloud.githubusercontent.com/assets/8839749/19222948/cdb004f4-8e6c-11e6-943e-4e95880c59eb.png)
- F# (*.fsproj): 
![image](https://cloud.githubusercontent.com/assets/8839749/19222954/e8ca759e-8e6c-11e6-9ae3-46356e41355e.png)

P.S.: I thought that maybe this icon would look more appealing (especially with dark VSCode background because of white border): ![image](http://i.imgur.com/ENdhqxw.png)

**Comment by EmmanuelBeziat** [comment]
Changed it. Thanks!
