### ISSUE TITLE
add an icon for gulpfile

### ISSUE THREAD

**Issue by diabloevagto** [EmmanuelBeziat/vscode-great-icons#40]
* specific filename gulpfile.babel.js support on gulp ver.3.9.0
* Specific files names: gulpfile.babel.js

if use "gulpfile.babel.js" , run babel translate before gulp.

example like it.
https://gist.github.com/stephensauceda/ce81e95c6f6c5747d8aa

**Comment by EmmanuelBeziat** [comment]
Hi,
Here you go in the new **1.1.46** version. Thanks!
