### ISSUE TITLE
Nunjucks icons

### ISSUE THREAD

**Issue by Flerox** [EmmanuelBeziat/vscode-great-icons#42]
## Format to support

* Nunjucks template file (https://mozilla.github.io/nunjucks/)
* Icon: (https://cloud.githubusercontent.com/assets/149081/10471375/3e6b4c78-71e3-11e5-90c9-77916b5b13de.jpg)
* Files extensions: `*.nunjucks, *.nunjs, *.nj, *.njhtml, *.njk
`

**Comment by EmmanuelBeziat** [comment]
Hi,
Here you go: check the new 1.1.48 version! :)
Thanks
