### ISSUE TITLE
Feature: Custom Overrides Preserved Between Upgrades

### ISSUE THREAD

**Issue by karlfus** [EmmanuelBeziat/vscode-great-icons#46]
Hi, your extension is fantastic, and it improves my day-to-day life as a coder immeasurably. I've tried all the other icon packs and yours is the bomb. One of the main reasons is your great support for test (.spec) files which makes a big difference when I'm "visually grepping" a bunch of open tabs.

You are updating/upgrading the extension frequently which is great...but presents an issue of its own. There are a few icons in your collection that are not my favorites, particularly the typescript and javascript icons. I end up borrowing these from "simple icons" (svg files) and editing the icons.json file on every upgrade in order to preserve my "custom" icon overrides. I'm going to guess I'm not the only one of your users doing this.

I'm not sure if this is possible in the VSCode extension ecosystem, but it would be fantastic for me (and I presume others) if there were some way to customize some icons with my own preferences and then *maintain those customizations between upgrades*. 

Perhaps one way to do this would be with a separate customizations.json and custom_icons folder, though I'm not sure how this would work internally. If it were possible to run code upon installation (I'm not sure this is possible but I doubt it) it would be possible to preserve any customizations programmatically by scanning the icons.json and the icons folders. 

In my particular case, another method that would work would be if svg and png files were treated equivalently if the extension were omitted from the icons.json file, but I'm not sure if this is feasible to implement (or if it would solve the problem generically enough).

Just a suggestion that would make the extension that much more universally fabulous! Meanwhile keep up the great work! By the way we spend most every August in Saint-Florent (Corse), vive la sud de France!

**Comment by EmmanuelBeziat** [comment]
Hi,
Thanks for your suggestion. I think this would be a great addition.

I don't really know what's possible through this, I'm going to check. Maybe having a second json / folder could be good, but I don’t know if VScode would support some sort of include, nor if it wouldn't simply erase it in the upgrade process.

I’ll do some tests, and I’ll let you know.

**Comment by EmmanuelBeziat** [comment]
Well… Fuck. 😞 

![2017-04-15-jt9hv](https://cloud.githubusercontent.com/assets/6781337/25057799/4eb8ceca-2173-11e7-8016-b6009f264218.jpg)

The extensions folders are marked with the current version, and simply removed on upgrade.

Sorry though, I had to make a new upgrade… I feel bad knowing that it messes up your config each time. 

I’m going to check if it could be possible to define some custom icons via the settings of VScode… There should be a way!

**Comment by EmmanuelBeziat** [comment]
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration

**Comment by karlfus** [comment]
So contributes.configuration looks like a path forward then? I'm curious if there is any way to define custom icons from there.

**Comment by EmmanuelBeziat** [comment]
I'm thinking about it. Didn't find a way yet, but I think this could be the only possible option to get an uprade-proof solution.

**Comment by karlfus** [comment]
I guess another option is to have a piece of code that runs offline to merge the new and old versions. Is there any way to run code on installation, ala Squirrel? Otherwise maybe just a script I could run manually...which to be fair I could write myself.

**Comment by EmmanuelBeziat** [comment]
> Is there any way to run code on installation

That could be a good point! Dunno if this is possible, I’ll check on this too.

**Comment by EmmanuelBeziat** [comment]
https://github.com/Microsoft/vscode/issues/25070#event-1051221627

Well, I'm sorry…

If you create a script, be sure to publish it on github, I'll put a link in the description for evrtyone to see it!
