### ISSUE TITLE
R language

### ISSUE THREAD

**Issue by seraku24** [EmmanuelBeziat/vscode-great-icons#47]
## R language

* [R (official site)](https://www.r-project.org/) and [R (Wikipedia)](https://en.wikipedia.org/wiki/R_(programming_language))
* [![Official icon](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/R_logo.svg/310px-R_logo.svg.png) Link to official icon (PNG and SVG available)](https://www.r-project.org/logo/)
* Files extensions: `*.r, *.R` (source files) `*.RData, *.rda, *.rds` (data files)
* Specific files names: `.Rprofile` (initialization file, do note the leading period)

---

I have included the standard extensions for serialized data objects, as they were listed in the Wikipedia article.  Since they are just data stores, would it make sense to just reuse the existing database icon for those files?

**Comment by EmmanuelBeziat** [comment]
Hi,
The icon has been added to the new 1.1.51 version :)

Thanks!
