### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by seraku24** [EmmanuelBeziat/vscode-great-icons#48]
## CMake

* [CMake (official site)](https://cmake.org/) and [CMake (Wikipedia)](https://en.wikipedia.org/wiki/CMake)
* [![Official icon](https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Cmake.svg/240px-Cmake.svg.png) Link to SVG on Wikimedia](https://commons.wikimedia.org/wiki/File:Cmake.svg)
* Files extensions: `*.cmake`
* Specific files names: `CMakeLists.txt`

---

Of course, simply reusing the existing Makefile icon is a perfectly fine option too.  I just don't like looking at the boring blue generic file icon.  `(:`

**Comment by EmmanuelBeziat** [comment]
Hi,
The icon has been added to the new 1.1.51 version :)

Thanks!

**Comment by seraku24** [comment]
Just updated.  Looks like the system is case-sensitive for specific file names.  The usual spelling is `CMakeLists.txt` (note the upper-case `M`).

Otherwise, again, great work on getting those icons to look so good at the small size.  `(:`

**Comment by EmmanuelBeziat** [comment]
Woops! I’ll correct in a few minutes.

**Comment by EmmanuelBeziat** [comment]
Should be good now :)

**Comment by seraku24** [comment]
Sorry, but I think there's another issue at play here.  I thought it was case-sensitivity, but I can see now that `icons.json` lists some files such as `license` in all lower-case, but it works just fine when I use all upper-case.  If you take a look at this screen shot, you can see that the `CMakeLists.txt` files are not getting the icon but everything else is working as expected.  (Ignore `CMakeCache.txt` which is just a build artifact.)

![vscode-great-icons-cmake-issue](https://cloud.githubusercontent.com/assets/20533271/25249227/02f712ce-25c6-11e7-86db-815f88b3a8d9.png)

For reference, here are the details from my VSCode installation:
```
~ $ code --version
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e
~ $ code --list-extensions --show-versions
dbaeumer.vscode-eslint@1.2.8
emmanuelbeziat.vscode-great-icons@1.1.52
flet.vscode-semistandard@1.1.2
ms-vscode.cpptools@0.10.5
twxs.cmake@0.0.17
```

I was thinking that it might be because of the `.txt` file extension but I cannot find it mentioned explicitly within `icons.json`.  I wonder if this is a problem with VSCode itself handling the `.txt` file itself and is causing problems.  Any ideas?  Or should I open an issue against VSCode at this point?

**Comment by EmmanuelBeziat** [comment]
That’s really strange. I’ll have a look, I probably messed up Something.

**Comment by EmmanuelBeziat** [comment]
Let's try again with the 1.1.53 version. Tell me if it's ok?

**Comment by seraku24** [comment]
Seems to be working, so that's good.  Not sure why you had to make the changes you did to get it working, since the original code *should* have worked from the beginning.  Best probably not to ask too many questions, lest the code gremlins decide to break things again.  `(:`

**Comment by EmmanuelBeziat** [comment]
Sure thing ;) It seems to work better if everything is lowercase.
