### ISSUE TITLE
.ctp (CakePHP templates)

### ISSUE THREAD

**Issue by Xety** [EmmanuelBeziat/vscode-great-icons#49]
## Format to support

* Official site: https://cakephp.org
* Official icon: http://clement-cavaroc.fr/assets/images/profil/p5C2_6xM.jpg
* Files extensions: *.ctp
* Specific files names: none

**Comment by EmmanuelBeziat** [comment]
Hi,
The icon has been added to the new 1.1.51 version :)

Thanks!
