### ISSUE TITLE
Duplicate icons ?

### ISSUE THREAD

**Issue by imacnu** [EmmanuelBeziat/vscode-great-icons#5]
![screenshot 2016-10-10 11 57 06](https://cloud.githubusercontent.com/assets/5846051/19232549/b27f9298-8ee0-11e6-99db-31459d086ae9.png)

**Comment by EmmanuelBeziat** [comment]
Hi,
That's really weird. Do you have another icon pack installed? Which one?

**Comment by imacnu** [comment]
![screen shot 2016-10-10 at 12 13 09](https://cloud.githubusercontent.com/assets/5846051/19232960/f7089606-8ee2-11e6-9aad-b652772b91f3.png)

**Comment by imacnu** [comment]
Last visual code update (1.6.0) resolve it. Thanks
