### ISSUE TITLE
A folder with a file named package.json means PACKAGE, suggest to use an icon to mean package

### ISSUE THREAD

**Issue by frank6600** [EmmanuelBeziat/vscode-great-icons#50]
A folder with a file named package.json means PACKAGE, 
suggest to use an icon to mean package

more than that,

a folder with package folders means a workspace,
suggest to use an icon to mean workspace.

thx.

**Comment by EmmanuelBeziat** [comment]
Hi,

I'm not sure about what you're suggesting…? You’d like to have a specific folder icon if it contains a specific file?

**Comment by frank6600** [comment]
Hi,


Yes, you got it!
Thanks for asking.


Frank




------------------ 原始邮件 ------------------
发件人: "Emmanuel Béziat";<notifications@github.com>;
发送时间: 2017年4月24日(星期一) 晚上8:46
收件人: "EmmanuelBeziat/vscode-great-icons"<vscode-great-icons@noreply.github.com>; 
抄送: "Frank"<frank6600@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [EmmanuelBeziat/vscode-great-icons] A folder with a file namedpackage.json means PACKAGE, suggest to use an icon to mean package (#50)




Hi,
 
I'm not sure about what you're suggesting…? You’d like to have a specific folder icon if it contains a specific file?

**Comment by EmmanuelBeziat** [comment]
Unfortunately I don't think this would be possible ; this is just a json list of name folders / files. If you know an icon set that do this, please give me a link so I could look at the code :)

**Comment by frank6600** [comment]
> Unfortunately I don't think this would be possible ; this is just a json list of name folders / files.



Well, what do you mean a json list of name folders/files cannot support you to make an icon to present package?


However, if you say it's not possible, ok, I have no other opinions.


thx.


frank


------------------ 原始邮件 ------------------
发件人: "Emmanuel Béziat";<notifications@github.com>;
发送时间: 2017年4月25日(星期二) 凌晨0:34
收件人: "EmmanuelBeziat/vscode-great-icons"<vscode-great-icons@noreply.github.com>; 
抄送: "Frank"<frank6600@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [EmmanuelBeziat/vscode-great-icons] A folder with a file named package.json means PACKAGE, suggest to use an icon to mean package (#50)




Unfortunately I don't think this would be possible ; this is just a json list of name folders / files. If you know an icon set that do this, please give me a link so I could look at the code :)

**Comment by EmmanuelBeziat** [comment]
Well, the json list works like this: 

```json
{
  "foldername": "folderIcon.png",
  "fileextension": "extensionIcon.png"
}
```
I can only give icons directly on elements by their name or their extension.

So if I understand your request correctly, you want to put an icon on a folder if it contains a certain file. That is not possible this way.

If I misunderstand you, don't hesitate to correct me :)
