### ISSUE TITLE
.volt (Phalcon Template)

### ISSUE THREAD

**Issue by Xety** [EmmanuelBeziat/vscode-great-icons#53]
## Format to support

* Official site: https://phalconphp.com
* Official icon: 
![687474703a2f2f692e696d6775722e636f6d2f355445695853352e706e67](https://cloud.githubusercontent.com/assets/8210023/25510218/c059d218-2bbe-11e7-8ca6-4c70c46cb069.png)
* Files extensions: *.volt

**Comment by EmmanuelBeziat** [comment]
Hi,
Check it out in the new 1.1.53 version! :)

**Comment by Xety** [comment]
I don't know if you noticed my comment, but :
https://github.com/EmmanuelBeziat/vscode-great-icons/commit/5b7704662d126e4da577fe6061cbf5c5a206e7c2#commitcomment-21963118

**Comment by EmmanuelBeziat** [comment]
Woups, sorry. I'll get this asap.
