### ISSUE TITLE
.vscode directory

### ISSUE THREAD

**Issue by Xety** [EmmanuelBeziat/vscode-great-icons#54]
## Format to support

* https://code.visualstudio.com/
* Official icon : 
![vscode](http://budiirawan.com/wp-content/uploads/2015/12/vscode-logo.png)
* Directory extensions: *.vscode

**Comment by EmmanuelBeziat** [comment]
Hi,
Check it out in the new 1.1.53 version! :)

**Comment by EmmanuelBeziat** [comment]
I've enhanced this a bit in the new 1.1.54 version.
