### ISSUE TITLE
Add option to disable folder icons

### ISSUE THREAD

**Issue by scottsb** [EmmanuelBeziat/vscode-great-icons#55]
Some applications like Magento 2 are very folder-y, and it gets hard to see the files for the trees. Would be great to have an option to disable them like vscode-icons or vscode-material-icon-theme has.

**Comment by EmmanuelBeziat** [comment]
Hi,
I'll check the sets you  mentionned to get a clear view of how they done this, and I'll do it too. I'm glad if I can help users to customize their IDE. Thanks!

**Comment by EmmanuelBeziat** [comment]
I've spent the night refactoring all the code so this could be possible.
And at the time… It don't work yet. But it seems to be just a minor bug. Still, this is a great improvement. I'll let you know as soon as I'll have got this to work.

**Comment by scottsb** [comment]
Thanks for working on it!

**Comment by EmmanuelBeziat** [comment]
I’m sorry, I’ve had less time to work on it. But this is still on my mind.

**Comment by So1ene** [comment]
Is there an update on this? I love every icon except the folder icons, I get confused with file icons and just want to disable them so I can more easily determine what is a folder and what is a file.
