### ISSUE TITLE
HI - Suggestion to keys and certs.

### ISSUE THREAD

**Issue by Davidpsj** [EmmanuelBeziat/vscode-great-icons#56]
Hi!

I'd like to suggest to you, creating icons for .ppk, .pem, and .cer extension files.

Thanks!

**Comment by EmmanuelBeziat** [comment]
Hi,
ppk and pem already have an icon ; i'll add one for .cer quickly :)

**Comment by EmmanuelBeziat** [comment]
It's done. Check out the new 2.0.2 version. :)
