### ISSUE TITLE
Dockerfile icon is not the Docker Logo

### ISSUE THREAD

**Issue by pjlamb12** [EmmanuelBeziat/vscode-great-icons#57]
## Format to support

* [Dockerfile](https://www.docker.com/)
* Already in your icons folder
* Dockerfile, Dockerfile.*

I looked through and see that you have a setting that should add the Docker icon, but it doesn't do it on my Dockerfile or Dockerfile.environment file

**Comment by EmmanuelBeziat** [comment]
Hi,
Okay, i'll add this soon :)

**Comment by EmmanuelBeziat** [comment]
It's done. Check out the new 2.0.2 version. :)
Tell me if there's some extensions missing.
