### ISSUE TITLE
Problem setting icon theme: {0}

### ISSUE THREAD

**Issue by evanwarner** [EmmanuelBeziat/vscode-great-icons#59]
With the 1.12 VSCode update, this icon theme no longer works. I can install other icon themes just fine, but I get the message **Problem setting icon theme: {0}** when trying to set this theme.

**Comment by EmmanuelBeziat** [comment]
Hi,
That's really weird, I don't have this issue either on macOS or Windows… But I thought I've seen this before, did you try to uninstall and reinstall the theme?

What's your system? Was the theme installed before the update?

**Comment by evanwarner** [comment]
Ah yeah, uninstall, reload, reinstall fixed it. It was my active theme before updating VSCode. OSX 10.11.6

**Comment by EmmanuelBeziat** [comment]
I'll keep that in mind in case it happens again. Thanks :)
