### ISSUE TITLE
Additional icons

### ISSUE THREAD

**Issue by christophano** [EmmanuelBeziat/vscode-great-icons#6]
I would love it if the following icons could be included:

<img src="http://blog.tech-fellow.net/content/images/2015/08/nuget.png" width="20" /> Nuget (.nuspec, .nupkg)

<img src="https://acom.azurecomcdn.net/80C57D/cdn/mediahandler/acomblog/media/Default/blog/powershell-logo.png" width="20" /> Powershell (.ps1)

<img src="https://raw.githubusercontent.com/cake-build/graphics/master/png/cake-medium.png" width="20" /> Cake (.cake)

**Comment by EmmanuelBeziat** [comment]
Sorry, I'm a bit late. It's done!
