### ISSUE TITLE
Conflicts with Material Icon Theme

### ISSUE THREAD

**Issue by PKief** [EmmanuelBeziat/vscode-great-icons#60]
I just wanted to mention, that I've installed both your extension and the [Material Icon Theme](https://github.com/PKief/vscode-material-icon-theme). After that I noticed that the "toggle folders"-command of the material icon theme is no longer available:

![m_icons_1](https://cloud.githubusercontent.com/assets/12248527/25774316/2e895c70-328d-11e7-8c88-aa3487cd88f8.PNG)

I tried out the same command for your theme and it toggled the folders of the material icon theme:

![image](https://cloud.githubusercontent.com/assets/12248527/25774384/da0c16d2-328d-11e7-81f2-35e8a32ee413.png)

I uninstalled your extension and the command for the material icons is back:

![m_icons_2](https://cloud.githubusercontent.com/assets/12248527/25774367/9127e5f4-328d-11e7-8091-31ce555013e0.PNG)

--- 

In my opinion it is not done with just grabbing someone else's code, paste it in his own icon extension and push it to the marketplace as you did with this [commit](https://github.com/EmmanuelBeziat/vscode-great-icons/commit/06d4b2d4cf1a36f0f6b18e013ba989137a9cde4e). 

If you run your extension you'll see this error message, that there will be some conflicts:

![commands_already_exists](https://cloud.githubusercontent.com/assets/12248527/25774432/c6d6401e-328e-11e7-8272-bbc3f18b1103.PNG)

Please update and customize your extension especially the command ids to fix this issue!

**Comment by EmmanuelBeziat** [comment]
#55 Related

------------------

Hi @PKief

I didn‘t had the time to check the issue yet. Still, I‘m aware of it and willing to clean it up in order to keep only what‘s needed and have it working.

I‘ll take some time this night to get this done and avoid any conflict and produce different sources.

Thanks!

**Comment by EmmanuelBeziat** [comment]
Well, in order to have much time to put this clear, I made a rollback to a previous state. There‘s no command at all, so it won‘t produce any conflict.
