### ISSUE TITLE
[Icon request] gitlab ci icon

### ISSUE THREAD

**Issue by ausir0726** [EmmanuelBeziat/vscode-great-icons#61]
## Format to support
if can add gitlab-ci icon will be helpful . really thanks !!

* [Type of file]
gitlab-ci-cd yaml file

* Official icon (link or image)
https://about.gitlab.com/features/gitlab-ci-cd/

* Specific files names: 
.gitlab-ci.yml

![image](https://cloud.githubusercontent.com/assets/7247064/26032792/a0ea5cdc-38ce-11e7-9c8b-e2a3281c8f45.png)

**Comment by EmmanuelBeziat** [comment]
Hi,

Here it comes! Check out the new 2.1.3 version! Thanks :)

**Comment by ausir0726** [comment]
@EmmanuelBeziat 

the extension is `.yml`
I update to 2.1.3 , I seen the fox , but extension file name need `.yaml`
is possible add `.yml` extension file name ?

![image](https://cloud.githubusercontent.com/assets/7247064/26156439/f10c05ea-3b48-11e7-9a0d-483a8701ca10.png)


thanks.

**Comment by EmmanuelBeziat** [comment]
Ooh, I see.
Here it is. :) Check the 2.1.4, it's now ok!

**Comment by ausir0726** [comment]
thanks !

that's great and awesome extension !

**Comment by EmmanuelBeziat** [comment]
Glad you like it! :)
