### ISSUE TITLE
Arduino patch (*.ino) icon

### ISSUE THREAD

**Issue by JoaoAlpinista** [EmmanuelBeziat/vscode-great-icons#63]
## Format to support

* Arduino Patch: https://www.arduino.cc/en/reference/homePage
* There are a few versions. I like this one: https://www.arduino.cc/en/uploads/Main/Create-software1.svg
* Files extensions: *.ino

**Comment by EmmanuelBeziat** [comment]
Hi,
There you go, check out the new 2.1.6 version! :)
