### ISSUE TITLE
Support dockerfile language identifier

### ISSUE THREAD

**Issue by nhoekstra** [EmmanuelBeziat/vscode-great-icons#67]
Would it be possible to add dockerfile to the languageIds section? Right now **dockerfile** and **dockerfile.environment** correctly resolve to the docker icon but other suffixes, i.e. **dockerfile.build** do not. Adding the language identifier would allow proper detection of all dockerfiles.

There's a few other language identifiers that may also be useful to add. There's a full list [here.](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers)

**Comment by EmmanuelBeziat** [comment]
Hi,

Just check the new version 2.1.8, this is added :)
Please note that you’ll need to have a docker extension in VScode for it to work, otherwise the language ID won't be recognized.
