### ISSUE TITLE
Add unsaved/temp file support

### ISSUE THREAD

**Issue by JayYa** [EmmanuelBeziat/vscode-great-icons#69]
## Format to support

* Unsaved file

**Comment by EmmanuelBeziat** [comment]
Hi,

Which icon would you find relevant for this?

**Comment by JayYa** [comment]
For example, I create a json file that unsaved, the file's icon should be 'json'.

**Comment by EmmanuelBeziat** [comment]
There’s no way to just `file -> new` and it would automatically knew wich language you wish to use. 

There’s two options:
* As soon as you set a language on new a file, the icon is automatically set on the tab.
* You should create a file in the files view directly, setting its extension, so it would work too.

If I misunderstood what you ask, please let me know :)

**Comment by JayYa** [comment]
![file](https://user-images.githubusercontent.com/9401705/27266541-a4875558-54d4-11e7-8cff-96d48e8d3214.png)
I have created a file and set the language, but that icon was not change.
Bug?

**Comment by EmmanuelBeziat** [comment]
That’s strange… It totally work for me, on 2 differents PC and a mac.

Please try to remove and reinstall the plugin?

**Comment by JayYa** [comment]
Some icons will change but some not. 😥

**Comment by EmmanuelBeziat** [comment]
That’s very weird… I tried with others icons sets, and it does work well too. Seems like, for a reason, your VS Code is blocking this feature. What if you try to disable most of plugins (you can do it without remove them)?
