### ISSUE TITLE
New yarn icons please

### ISSUE THREAD

**Issue by MichaelBowenSc** [EmmanuelBeziat/vscode-great-icons#7]
Please add YarnPkg icon support (https://github.com/yarnpkg/yarn)

1. yarn.lock 
2. .yarnclean

![yarnlock](https://cloud.githubusercontent.com/assets/8138358/19400275/7543e302-9223-11e6-8c59-ce93ded26e51.png)
![yarnrc](https://cloud.githubusercontent.com/assets/8138358/19400289/7d8c03be-9223-11e6-958c-0a020c1e934a.png)

**Comment by EmmanuelBeziat** [comment]
Just added this! Thanks for your request.

**Comment by MichaelBowenSc** [comment]
thanks.

**Comment by EmmanuelBeziat** [comment]
Was buggy, just pushed a debug.
