### ISSUE TITLE
Icons for GLSL files

### ISSUE THREAD

**Issue by nixegend** [EmmanuelBeziat/vscode-great-icons#70]
GLSL - https://www.khronos.org/opengl/wiki/OpenGL_Shading_Language
Files extensions: *.glsl, *.vs, *.fs, *.frag, *.vert

**Comment by EmmanuelBeziat** [comment]
Hi,

It’s done. Check out the new 2.1.9 version!

Unfortunately, the .fs file format is already used for fsharp files…

**Comment by HuskyNator** [comment]
I'd like to request further additions:
The `.geom` `.tesc` `.tese` and `.comp` extensions are common glsl extensions for use with opengl
See also: https://stackoverflow.com/a/26531467/12640952

I could also reference GLSL Lint's supported extensions, though I am uncertain about the prevelance of extensions like `.rchit` and `.task` (https://github.com/hsimpson/vscode-glsllint)

**Comment by EmmanuelBeziat** [comment]
Hi @HuskyNator 

It's done ; check the new v2.1.90!
