### ISSUE TITLE
Icon for the Dart programming language

### ISSUE THREAD

**Issue by rinukkusu** [EmmanuelBeziat/vscode-great-icons#72]
## Format to support

* [Dart](https://www.dartlang.org/)
* https://github.com/dart-lang/logos/blob/master/logos_and_wordmarks/dart-logo.png
* Files extensions: *.dart
* Specific files names: none

Hi, I'd fancy an icon for my `*.dart` files instead of the generic placeholder thingy:

![image](https://user-images.githubusercontent.com/804848/28116926-852e57d0-670b-11e7-8e1b-f4b08c9b28cf.png)

Thanks in advance!! ❤️

**Comment by EmmanuelBeziat** [comment]
Hi,
The dart icon have been added to the new version!

**Comment by rinukkusu** [comment]
Looking good, thanks :heart_eyes:

**Comment by rinukkusu** [comment]
Hm, on a second look, that's not the current official icon and does look too flashy anyway. Do you mind using the one I provided?

**Comment by zabusm** [comment]
IMHO the dart icon in vscode-great-icons looks great!

**Comment by rinukkusu** [comment]
I actually want a neat icon for Dart - please no trolling @zabusm ;__;

**Comment by EmmanuelBeziat** [comment]
Here you go! :) check the new v.2.1.12!

**Comment by rinukkusu** [comment]
Now that pleases my eyes! :) 👍
