### ISSUE TITLE
add ico for RStudio files

### ISSUE THREAD

**Issue by gitzhuoer** [EmmanuelBeziat/vscode-great-icons#74]
- RStudio project
- ![7](https://user-images.githubusercontent.com/15871952/28273203-417f92f4-6b40-11e7-8a67-a32076ea6361.png)
- .Rproj
- I have rename the image to `*.png` in order to upload it to GitHub. You need to rename back to `*.ico` after download that image

**Comment by EmmanuelBeziat** [comment]
Here you go! :) check the new v.2.1.12!

**Comment by gitzhuoer** [comment]
Thank you so much!
