### ISSUE TITLE
Solidity files

### ISSUE THREAD

**Issue by Mahesh1** [EmmanuelBeziat/vscode-great-icons#75]
## Format to support
.sol
* [Type of file](http://linktoofficialsite.com)
Solidity
* Official icon (link or image)
* Files extensions: *.ext1, *.ext2 
.sol
* Specific files names: (if required; for example: gulpfile.js) file1.ext, file2.ext

**Comment by EmmanuelBeziat** [comment]
Hi,

You can find it in the new version! Thanks.
