### ISSUE TITLE
Add monochrome/grayscale option

### ISSUE THREAD

**Issue by patrickcate** [EmmanuelBeziat/vscode-great-icons#78]
It would be nice if there was an option to display the icons as grayscale/monochrome, rather than with color. I find the wide variety of colors for the icons a bit distracting a times.

**Comment by EmmanuelBeziat** [comment]
Hi,
I'll watch about it, but I'm not sure there would be an easy way to do this easily. Beside, it would need a complete recoding of the plugin, as it is very simple for the moment; but I was already looking for a better integration way.

I'll keep it in mind and see what I can do.

**Comment by benbarber** [comment]
+1 Monochrome would be great

**Comment by patrickcate** [comment]
> I'll watch about it, but I'm not sure there would be an easy way to do this easily. Beside, it would need a complete recoding of the plugin, as it is very simple for the moment; but I was already looking for a better integration way.
> 
> I'll keep it in mind and see what I can do.

Thanks for all your work on this plugin! 

I don't know enough about how things are implemented in the plugin, but if there is a way to apply CSS to the icons, using the grayscale() CSS filter might work. 

https://developer.mozilla.org/en-US/docs/Web/CSS/filter#grayscale()_2
https://codepen.io/massiebn/pen/LNGdRW
https://css-tricks.com/snippets/css/monotone-image-css/

**Comment by RobJacobson** [comment]
Joining this thread from the future year of... 2021... to give this a big "plus 1!"

I really love this icon pack, but I'm also easily distracted by colors.  In addition to a "grayscale" mode, perhaps there could be a "desaturated" mode where the colors are dialed-back by 50%.
