### ISSUE TITLE
Add support for .http files

### ISSUE THREAD

**Issue by RobPethick** [EmmanuelBeziat/vscode-great-icons#79]
There is an extension that allows you to run HTTP requests from .http files.

AFAIK there is no official icon for the http file type. I thought maybe up/down arrows to symbolize request response

* [.http](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)
* Official icon (link or image) - none
* Files extensions: *.http

**Comment by EmmanuelBeziat** [comment]
Hi,
You'll find it in the new 2.1.15 version!
Thanks :)
