### ISSUE TITLE
React TypeScript icon (.tsx)

### ISSUE THREAD

**Issue by iwozzy** [EmmanuelBeziat/vscode-great-icons#8]
Could we please add a React TypeScript icon (.tsx)?

![image](https://cloud.githubusercontent.com/assets/4137844/19440431/bf101392-9436-11e6-90ed-25a5748c3464.png)

This is the seti icon which looks nice.

**Comment by EmmanuelBeziat** [comment]
There is an icon for typescript. Do you thing this should be more related to typescript (and then have the typescript icon), or to react (and then have the react icon)?

**Comment by iwozzy** [comment]
I see .tsx as an answer to .jsx so I'd associate .tsx with the same icon that .jsx is associated with

**Comment by EmmanuelBeziat** [comment]
Okay. I’ll publish this soon.

**Comment by iwozzy** [comment]
Thank you!

**Comment by EmmanuelBeziat** [comment]
It‘s done. The update will be available soon. Thanks!
