### ISSUE TITLE
Add support for Rollup config file (rollup.config.js)

### ISSUE THREAD

**Issue by mikirejf** [EmmanuelBeziat/vscode-great-icons#81]
## Format to support

* [Rollup](https://rollupjs.org)
* Official icon https://rollupjs.org/logo.svg
* Files extensions: `*.js`
* Specific files names: `rollup.config.js`

**Comment by EmmanuelBeziat** [comment]
Hi, sorry for the delay.

Here it is, check the new version :)

**Comment by mikirejf** [comment]
> Hi, sorry for the delay.
> 
> Here it is, check the new version :)

Looks great. Thanks! :D
