### ISSUE TITLE
.lua extension icon

### ISSUE THREAD

**Issue by eniallator** [EmmanuelBeziat/vscode-great-icons#82]
I'm a lua developer and it would be cool to me if the .lua extension was supported as even the default vscode seti theme doesn't have support for it.

**Comment by EmmanuelBeziat** [comment]
Hi,

The lua icon has been added recently: https://github.com/EmmanuelBeziat/vscode-great-icons/issues/80

Check that you have the latest version of the plugin. If some extensions are missing, please tell me wich ones :)

**Comment by eniallator** [comment]
ah right, thnx! and yeah, i'll definately say if i do find any missing icons :)

**Comment by EmmanuelBeziat** [comment]
Super :)
