### ISSUE TITLE
Hi, Icons are not supporting for my visual studio code , since i updated 

### ISSUE THREAD

**Issue by praveenbm9321** [EmmanuelBeziat/vscode-great-icons#84]
## Format to support

* [Type of file](http://linktoofficialsite.com)
* Official icon (link or image)
* Files extensions: *.ext1, *.ext2
* Specific files names: (if required; for example: gulpfile.js) file1.ext, file2.ext

**Comment by EmmanuelBeziat** [comment]
Hi,
Something may have went wrong during the update. Try to remove and reinstall the icons plugin, and reactivate it in Files → Settings
