### ISSUE TITLE
Support root folder icons

### ISSUE THREAD

**Issue by bpasero** [EmmanuelBeziat/vscode-great-icons#85]
VS Code will enable multi-root support for the upcoming October release (early November) and it would be great if vscode-great-icons would support root folder icons. See https://code.visualstudio.com/updates/v1_15#_icon-for-root-folders for more details.

**Comment by EmmanuelBeziat** [comment]
Hi,
Sure thing it will ;)

**Comment by EmmanuelBeziat** [comment]
Hi,
It's done. Check the new 2.1.17 version !
