### ISSUE TITLE
React .JSX file icon is weird

### ISSUE THREAD

**Issue by petrdanecek** [EmmanuelBeziat/vscode-great-icons#89]
Hi Emmanuel,

I really do like your icon set. The folders are great and makes big difference to others.
I'm working frequently with React .jsx files. The icon is there, but is kind of weird. It is not nice rendered and colors are not visible. I like more the icon from vscode-icons pack.

Is there any chance to make the react icon more "sharp" and colorful ?

Thanks,
Petr

**Comment by EmmanuelBeziat** [comment]
Hi,
Can you provide a screenshot please? It seems ok on my screens.

**Comment by petrdanecek** [comment]
Hi,

I'm not sure the screenshot is going to work as most likely it is going to
be displayed different way on your screen.
I'm able to see the comments, but not the comfortable way, it requires to
get closer to screen.

[image: Vložený obrázek 1]

I attached the panel from my Gmail as an example. Please refer to the
brightness of icons below which are visible well.
[image: Vložený obrázek 2]

Note: I do have 23" Dell LCD screen with factory settings (50% contrast).

Thanks,
Petr

2017-11-03 12:18 GMT+01:00 Emmanuel Béziat <notifications@github.com>:

**Comment by EmmanuelBeziat** [comment]
Hi,

I can't see your pics, unfortunately.

I've tried on some various setups now, from different PC, different OS, different screens… I can't see much.

Anyway I'll try to recreate the icon for the next update, let me know if it's better then.

**Comment by petrdanecek** [comment]
Hi there,

attaching the screenshot to the email

[image: Vložený obrázek 1]


The JSX icons from some other icons pack:
[image: Vložený obrázek 2]

Hope it helps,
Thanks,
Petr

2017-12-06 22:35 GMT+01:00 Emmanuel Béziat <notifications@github.com>:

**Comment by EmmanuelBeziat** [comment]
Hi @petrdanecek 
It don't seem to work if you post a picture by answering from an email. You might try directly in github. :) 

But I'll let you know once I'll change the icon (will try this afternoon), and I'll let you check if it's better.

**Comment by EmmanuelBeziat** [comment]
Check out the new 2.1.22 version :)
