### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by teckays** [EmmanuelBeziat/vscode-great-icons#90]
* [GraphQL](http://graphql.org/)
* Official icon (https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/GraphQL_Logo.svg/1024px-GraphQL_Logo.svg.png)
* Files extensions: *.gql, *.graphql

Thank you.

**Comment by EmmanuelBeziat** [comment]
Hi,
Check out the new 2.1.20 version :)

**Comment by teckays** [comment]
@EmmanuelBeziat would be gold if you could publish it ;)

**Comment by EmmanuelBeziat** [comment]
Sorry, there’s a token issue. Thanks, if you didn’t tell I wouldn’t have noticed. Here you go!
