### ISSUE TITLE
Add support for Prettier config files

### ISSUE THREAD

**Issue by mikirejf** [EmmanuelBeziat/vscode-great-icons#91]
## Format to support

* [Prettier config](https://prettier.io/)
* https://prettier.io/icon.png
* Files extensions: ```A .prettierrc file, written in YAML or JSON, with optional extensions: .yaml/.yml/.json/.js.```

* Specific files names: `prettier.config.js`

**Comment by EmmanuelBeziat** [comment]
Hi,
Check out the new 2.1.20 version, and tell me if it misses files :)

**Comment by rwu823** [comment]
Hi @EmmanuelBeziat 

![image](https://user-images.githubusercontent.com/890063/34028602-2f06236a-e19f-11e7-90f4-73c45fd80941.png)


It doesn't work for me. 

my VSCode Great Icons is `2.1.21`

**Comment by EmmanuelBeziat** [comment]
Hi @rwu823 

It misses this filename pattern, it seems. I’ll handle this soon. Thanks!

**Comment by EmmanuelBeziat** [comment]
Check out the new 2.1.22 version :)
