### ISSUE TITLE
vscode-great-icons has a strange behavior when scroll or fold/unfold treeview file

### ISSUE THREAD

**Issue by Davidpsj** [EmmanuelBeziat/vscode-great-icons#92]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
githistory|don|0.2.3
vscode-great-icons|emm|2.1.20
debugger-for-phantomjs|ira|0.1.1
webpack|jer|2.0.2
vscode-apache|mrm|1.1.1
team|ms-|1.122.0
debugger-for-chrome|msj|3.5.0

---

Steps to Reproduce:

1. Save workspace and add some folders.
2. unfold some directories in both projects folder
3. create, rename some files inside folders
4. scroll with mouse
5. collapse and uncollapse some structure in tree and see a crazy behavior display.

**Comment by EmmanuelBeziat** [comment]
Hi,

I didn't succeed to reproduce that. Are you having the same issue with any other icon set? I'm not sure I can help with that, sorry.
