### ISSUE TITLE
Allow configuration to hide explorer arrows

### ISSUE THREAD

**Issue by cpgo** [EmmanuelBeziat/vscode-great-icons#93]
According to https://github.com/Microsoft/vscode/issues/25655 we can set `"hidesExplorerArrows":true` on the extension.
Is it possible to allow this flag on the user settings?

**Comment by iamstevendao** [comment]
please make this feature, I also desperately need it

**Comment by EmmanuelBeziat** [comment]
Hi,

I’ll do it as soon as I can, but it needs some refactoring for the plugin. I can’t tell for sure when it wil be done.

Sorry for the delay.

**Comment by iamstevendao** [comment]
any news yet?

**Comment by andremacola** [comment]
1 - Just open the file _vscode-insiders/extensions/emmanuelbeziat.vscode-great-icons-2.1.22_
2 - Add `"hidesExplorerArrows":true,` before the `"iconDefinitions"` the beginning. No need to refactoring.

**Comment by EmmanuelBeziat** [comment]
@andremacola oh, thanks! Thought this was requiring much work, as for allowing install options and stuff.

It's done then!

**Comment by EmmanuelBeziat** [comment]
I'm sorry, but I had to revert back this update (https://github.com/EmmanuelBeziat/vscode-great-icons/issues/96).

The change suggested by @andremacola works, but don't allow users to chose. This is what I meant when I was talking about refactoring: the plugin must be created in such a way it add configurations settings in vscode, to allow users entering their own settings in the settings tab. This can't be done from a json file, it must be initialized within a complete JS function, loading the plugin and so on.

**Comment by SeanRParker** [comment]
Any update on this? material-icon-theme has various settings flags, but your icons are way better.

**Comment by nesslopz** [comment]
Go ahead. Your work is amazing. I hope you could do this.

**Comment by mrleblanc101** [comment]
Is there a fork with this improvement somewhere ?

**Comment by shinebayar-g** [comment]
So it's never implemented?

**Comment by EmmanuelBeziat** [comment]
> So it's never implemented or is there some setting available?

@shinebayar-g Unfortunately no. I'd need to completely remake the icon set as a whole plugin, and I intended to keep it as simple as possible to be easy to add new icons…

It's still on my mind, but I can't make any announcement over a date or something.
