### ISSUE TITLE
__tests__ and __snapshots__

### ISSUE THREAD

**Issue by Biromain** [EmmanuelBeziat/vscode-great-icons#94]
## Folders for Facebook Jest

* [Facebook Jest](https://facebook.github.io/jest/)
* [https://facebook.github.io/jest/img/jest.svg](https://facebook.github.io/jest/img/jest.svg)
* Folders
  - `__tests__`
  - `__snapshots__`

**Comment by EmmanuelBeziat** [comment]
Hi @Biromain 

Just to be sure, it's meant to be folders?

**Comment by Biromain** [comment]
Hi,
Yeap like that 
![](https://i.imgur.com/1KLAIMR.png)

Thank you for the really good icons theme. 👍

**Comment by EmmanuelBeziat** [comment]
There you go,

Check the new 2.1.21 version!

**Comment by Biromain** [comment]
Thanks, you are the best ᕦ(ò_óˇ)ᕤ 😄 I steal your tag, it's awesome.
