### ISSUE TITLE
It is pointless, if the icon of .mat file is the same of .m file.

### ISSUE THREAD

**Issue by DKJust** [EmmanuelBeziat/vscode-great-icons#95]
## Format to support

* [Type of file](http://linktoofficialsite.com)
* Official icon (link or image)
* Files extensions: *.m, *.mat
* Specific files names: (if required; for example: gulpfile.js) file1.ext, file2.ext

![image](https://user-images.githubusercontent.com/3668152/33815676-2502c9c4-de6e-11e7-85b7-c3a2d7b85e3e.png)

**Comment by EmmanuelBeziat** [comment]
Hi,

How do you think it should be? Can you provide an example of how others IDE / sets are handling this case?

Thanks!

**Comment by DKJust** [comment]
![image](https://user-images.githubusercontent.com/3668152/33873821-64d464f6-df57-11e7-81cb-bf844a31de51.png)
Like this example, the icons of .m and .mat are different, so that it's easy to find the .m files.

**Comment by EmmanuelBeziat** [comment]
Check out the new 2.1.22 version :)
