### ISSUE TITLE
how to show arrows on folders?

### ISSUE THREAD

**Issue by Yuliang-Lee** [EmmanuelBeziat/vscode-great-icons#96]
after last update, arrows missing,
how to show arrows on folders?

**Comment by clownvary** [comment]
Less intuitive than before , arrow should not be hidden.

**Comment by mwidmann** [comment]
For now I re-enabled the icon by changing line 2 in `icons.json` and setting `"hidesExplorerArrows": false` in the extension's folder.
This seems like an [official vscode](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_folder-icons-in-file-icon-themes) feature, but I wasn't able to find a setting to override this.

**Comment by Yuliang-Lee** [comment]
@mwidmann Where is the `icons.json` file?

**Comment by mwidmann** [comment]
I edited in the actual folder of the extension, on my Mac it is in `~/.vscode/extensions/emmanuelbeziat.vscode-great-icons-2.1.23`

**Comment by EmmanuelBeziat** [comment]
Okay, I reverted back to before, I'll find a better way to implement this, allowing users to chose.
